import { ServicePackage } from './servicePackage'

export const servicePackages: ServicePackage[] = [
  new ServicePackage('mypy-boto3-rds', 'RDS', 9776690),
  new ServicePackage('mypy-boto3-s3', 'S3', 9544202),
  new ServicePackage('mypy-boto3-appflow', 'Appflow', 6317453),
  new ServicePackage('mypy-boto3-redshift-data', 'RedshiftDataAPIService', 4670417),
  new ServicePackage('mypy-boto3-glue', 'Glue', 3205059),
  new ServicePackage('mypy-boto3-dynamodb', 'DynamoDB', 3023473),
  new ServicePackage('mypy-boto3-secretsmanager', 'SecretsManager', 2638063),
  new ServicePackage('mypy-boto3-sqs', 'SQS', 2607149),
  new ServicePackage('mypy-boto3-lambda', 'Lambda', 2586956),
  new ServicePackage('mypy-boto3-cloudformation', 'CloudFormation', 2027140),
  new ServicePackage('mypy-boto3-ec2', 'EC2', 1913374),
  new ServicePackage('mypy-boto3-sts', 'STS', 1810606),
  new ServicePackage('mypy-boto3-athena', 'Athena', 1295467),
  new ServicePackage('mypy-boto3-iam', 'IAM', 1120577),
  new ServicePackage('mypy-boto3-events', 'EventBridge', 1087287),
  new ServicePackage('mypy-boto3-ecr', 'ECR', 1023206),
  new ServicePackage('mypy-boto3-kinesis', 'Kinesis', 1022741),
  new ServicePackage('mypy-boto3-stepfunctions', 'SFN', 958563),
  new ServicePackage('mypy-boto3-ssm', 'SSM', 901627),
  new ServicePackage('mypy-boto3-apigateway', 'APIGateway', 893141),
  new ServicePackage('mypy-boto3-xray', 'XRay', 821228),
  new ServicePackage('mypy-boto3-signer', 'Signer', 820228),
  new ServicePackage('mypy-boto3-schemas', 'Schemas', 819402),
  new ServicePackage('mypy-boto3-appconfig', 'AppConfig', 774217),
  new ServicePackage('mypy-boto3-kms', 'KMS', 555293),
  new ServicePackage('mypy-boto3-sns', 'SNS', 544014),
  new ServicePackage('mypy-boto3-sagemaker', 'SageMaker', 437459),
  new ServicePackage('mypy-boto3-cloudwatch', 'CloudWatch', 420769),
  new ServicePackage('mypy-boto3-elbv2', 'ElasticLoadBalancingv2', 414805),
  new ServicePackage('mypy-boto3-dms', 'DatabaseMigrationService', 412738),
  new ServicePackage('mypy-boto3-logs', 'CloudWatchLogs', 408026),
  new ServicePackage('mypy-boto3-sso', 'SSO', 405901),
  new ServicePackage('mypy-boto3-ses', 'SES', 382117),
  new ServicePackage('mypy-boto3-ecs', 'ECS', 357069),
  new ServicePackage('mypy-boto3-cognito-idp', 'CognitoIdentityProvider', 353905),
  new ServicePackage('mypy-boto3-eks', 'EKS', 348217),
  new ServicePackage('mypy-boto3-lakeformation', 'LakeFormation', 335246),
  new ServicePackage('mypy-boto3-route53', 'Route53', 332142),
  new ServicePackage('mypy-boto3-servicecatalog', 'ServiceCatalog', 323295),
  new ServicePackage('mypy-boto3-emr', 'EMR', 283508),
  new ServicePackage('mypy-boto3-batch', 'Batch', 282163),
  new ServicePackage('mypy-boto3-firehose', 'Firehose', 279543),
  new ServicePackage('mypy-boto3-sagemaker-runtime', 'SageMakerRuntime', 276665),
  new ServicePackage('mypy-boto3-autoscaling', 'AutoScaling', 274371),
  new ServicePackage('mypy-boto3-efs', 'EFS', 244057),
  new ServicePackage('mypy-boto3-cognito-identity', 'CognitoIdentity', 237266),
  new ServicePackage('mypy-boto3-cloudfront', 'CloudFront', 224677),
  new ServicePackage('mypy-boto3-organizations', 'Organizations', 224653),
  new ServicePackage('mypy-boto3-codepipeline', 'CodePipeline', 220004),
  new ServicePackage('mypy-boto3-ce', 'CostExplorer', 219609),
  new ServicePackage('mypy-boto3-textract', 'Textract', 219026),
  new ServicePackage('mypy-boto3-opensearch', 'OpenSearchService', 218702),
  new ServicePackage('mypy-boto3-resourcegroupstaggingapi', 'ResourceGroupsTaggingAPI', 217761),
  new ServicePackage('mypy-boto3-acm', 'ACM', 215173),
  new ServicePackage('mypy-boto3-identitystore', 'IdentityStore', 210801),
  new ServicePackage('mypy-boto3-wafv2', 'WAFV2', 210543),
  new ServicePackage('mypy-boto3-cloudtrail', 'CloudTrail', 210406),
  new ServicePackage('mypy-boto3-application-autoscaling', 'ApplicationAutoScaling', 209526),
  new ServicePackage('mypy-boto3-elasticache', 'ElastiCache', 209497),
  new ServicePackage('mypy-boto3-pinpoint', 'Pinpoint', 208001),
  new ServicePackage('mypy-boto3-quicksight', 'QuickSight', 205947),
  new ServicePackage('mypy-boto3-sesv2', 'SESV2', 203674),
  new ServicePackage('mypy-boto3-dataexchange', 'DataExchange', 203633),
  new ServicePackage('mypy-boto3-mwaa', 'MWAA', 203555),
  new ServicePackage('mypy-boto3-kafka', 'Kafka', 202688),
  new ServicePackage('mypy-boto3-config', 'ConfigService', 202407),
  new ServicePackage('mypy-boto3-iot', 'IoT', 202182),
  new ServicePackage('mypy-boto3-es', 'ElasticsearchService', 200948),
  new ServicePackage('mypy-boto3-dynamodbstreams', 'DynamoDBStreams', 198362),
  new ServicePackage('mypy-boto3-scheduler', 'EventBridgeScheduler', 198071),
  new ServicePackage('mypy-boto3-bedrock', 'Bedrock', 197730),
  new ServicePackage('mypy-boto3-bedrock-runtime', 'BedrockRuntime', 197258),
  new ServicePackage('mypy-boto3-location', 'LocationService', 196585),
  new ServicePackage('mypy-boto3-transfer', 'Transfer', 195925),
  new ServicePackage('mypy-boto3-iot-data', 'IoTDataPlane', 194970),
  new ServicePackage('mypy-boto3-codebuild', 'CodeBuild', 194440),
  new ServicePackage('mypy-boto3-apigatewayv2', 'ApiGatewayV2', 193053),
  new ServicePackage('mypy-boto3-apigatewaymanagementapi', 'ApiGatewayManagementApi', 192396),
  new ServicePackage('mypy-boto3-service-quotas', 'ServiceQuotas', 191977),
  new ServicePackage('mypy-boto3-rds-data', 'RDSDataService', 191315),
  new ServicePackage('mypy-boto3-translate', 'Translate', 190882),
  new ServicePackage('mypy-boto3-transcribe', 'TranscribeService', 190766),
  new ServicePackage('mypy-boto3-redshift', 'Redshift', 190205),
  new ServicePackage('mypy-boto3-emr-serverless', 'EMRServerless', 189911),
  new ServicePackage('mypy-boto3-ec2-instance-connect', 'EC2InstanceConnect', 189828),
  new ServicePackage('mypy-boto3-codedeploy', 'CodeDeploy', 189703),
  new ServicePackage('mypy-boto3-support', 'Support', 189469),
  new ServicePackage('mypy-boto3-accessanalyzer', 'AccessAnalyzer', 189325),
  new ServicePackage('mypy-boto3-emr-containers', 'EMRContainers', 189233),
  new ServicePackage('mypy-boto3-codeartifact', 'CodeArtifact', 189035),
  new ServicePackage('mypy-boto3-securityhub', 'SecurityHub', 188872),
  new ServicePackage('mypy-boto3-neptunedata', 'NeptuneData', 188851),
  new ServicePackage('mypy-boto3-servicediscovery', 'ServiceDiscovery', 188335),
  new ServicePackage('mypy-boto3-synthetics', 'Synthetics', 188145),
  new ServicePackage('mypy-boto3-guardduty', 'GuardDuty', 187965),
  new ServicePackage('mypy-boto3-budgets', 'Budgets', 187961),
  new ServicePackage('mypy-boto3-network-firewall', 'NetworkFirewall', 187475),
  new ServicePackage('mypy-boto3-ebs', 'EBS', 187386),
  new ServicePackage('mypy-boto3-timestream-write', 'TimestreamWrite', 187265),
  new ServicePackage('mypy-boto3-elb', 'ElasticLoadBalancing', 186933),
  new ServicePackage('mypy-boto3-appsync', 'AppSync', 186744),
  new ServicePackage('mypy-boto3-marketplace-entitlement', 'MarketplaceEntitlementService', 186035),
  new ServicePackage('mypy-boto3-dlm', 'DLM', 185560),
  new ServicePackage('mypy-boto3-acm-pca', 'ACMPCA', 184988),
  new ServicePackage('mypy-boto3-timestream-query', 'TimestreamQuery', 184884),
  new ServicePackage('mypy-boto3-connect', 'Connect', 184666),
  new ServicePackage('mypy-boto3-cloudsearch', 'CloudSearch', 184585),
  new ServicePackage('mypy-boto3-backup', 'Backup', 184324),
  new ServicePackage('mypy-boto3-comprehend', 'Comprehend', 184165),
  new ServicePackage('mypy-boto3-cloudsearchdomain', 'CloudSearchDomain', 184127),
  new ServicePackage('mypy-boto3-appmesh', 'AppMesh', 184033),
  new ServicePackage('mypy-boto3-ram', 'RAM', 183992),
  new ServicePackage('mypy-boto3-rekognition', 'Rekognition', 183491),
  new ServicePackage('mypy-boto3-mediaconvert', 'MediaConvert', 183480),
  new ServicePackage('mypy-boto3-shield', 'Shield', 182939),
  new ServicePackage('mypy-boto3-sso-oidc', 'SSOOIDC', 182605),
  new ServicePackage('mypy-boto3-docdb', 'DocDB', 182536),
  new ServicePackage('mypy-boto3-route53resolver', 'Route53Resolver', 182500),
  new ServicePackage('mypy-boto3-sso-admin', 'SSOAdmin', 182497),
  new ServicePackage('mypy-boto3-amplify', 'Amplify', 182475),
  new ServicePackage('mypy-boto3-glacier', 'Glacier', 182465),
  new ServicePackage('mypy-boto3-bedrock-agent', 'AgentsforBedrock', 181954),
  new ServicePackage('mypy-boto3-opensearchserverless', 'OpenSearchServiceServerless', 181836),
  new ServicePackage('mypy-boto3-pricing', 'Pricing', 181624),
  new ServicePackage('mypy-boto3-comprehendmedical', 'ComprehendMedical', 181607),
  new ServicePackage('mypy-boto3-datasync', 'DataSync', 181477),
  new ServicePackage('mypy-boto3-ecr-public', 'ECRPublic', 181458),
  new ServicePackage('mypy-boto3-managedblockchain', 'ManagedBlockchain', 181234),
  new ServicePackage('mypy-boto3-greengrassv2', 'GreengrassV2', 181213),
  new ServicePackage('mypy-boto3-meteringmarketplace', 'MarketplaceMetering', 181213),
  new ServicePackage('mypy-boto3-polly', 'Polly', 181204),
  new ServicePackage('mypy-boto3-redshift-serverless', 'RedshiftServerless', 181158),
  new ServicePackage('mypy-boto3-appstream', 'AppStream', 181112),
  new ServicePackage('mypy-boto3-appconfigdata', 'AppConfigData', 180990),
  new ServicePackage('mypy-boto3-sdb', 'SimpleDB', 180829),
  new ServicePackage('mypy-boto3-account', 'Account', 180543),
  new ServicePackage('mypy-boto3-swf', 'SWF', 180524),
  new ServicePackage('mypy-boto3-codecommit', 'CodeCommit', 180515),
  new ServicePackage('mypy-boto3-grafana', 'ManagedGrafana', 180513),
  new ServicePackage('mypy-boto3-neptune', 'Neptune', 180510),
  new ServicePackage('mypy-boto3-ssm-sap', 'SsmSap', 180445),
  new ServicePackage('mypy-boto3-mediastore', 'MediaStore', 180037),
  new ServicePackage('mypy-boto3-s3control', 'S3Control', 179978),
  new ServicePackage('mypy-boto3-workspaces', 'WorkSpaces', 179974),
  new ServicePackage('mypy-boto3-workmail', 'WorkMail', 179853),
  new ServicePackage('mypy-boto3-directconnect', 'DirectConnect', 179839),
  new ServicePackage('mypy-boto3-pinpoint-email', 'PinpointEmail', 179802),
  new ServicePackage('mypy-boto3-databrew', 'GlueDataBrew', 179767),
  new ServicePackage('mypy-boto3-pi', 'PI', 179693),
  new ServicePackage('mypy-boto3-bedrock-agent-runtime', 'AgentsforBedrockRuntime', 179672),
  new ServicePackage('mypy-boto3-codestar-notifications', 'CodeStarNotifications', 179617),
  new ServicePackage('mypy-boto3-elasticbeanstalk', 'ElasticBeanstalk', 179597),
  new ServicePackage('mypy-boto3-serverlessrepo', 'ServerlessApplicationRepository', 179559),
  new ServicePackage('mypy-boto3-personalize', 'Personalize', 179508),
  new ServicePackage('mypy-boto3-chime', 'Chime', 179397),
  new ServicePackage('mypy-boto3-networkmanager', 'NetworkManager', 179395),
  new ServicePackage('mypy-boto3-ssm-incidents', 'SSMIncidents', 179359),
  new ServicePackage('mypy-boto3-ds', 'DirectoryService', 179347),
  new ServicePackage('mypy-boto3-compute-optimizer', 'ComputeOptimizer', 179328),
  new ServicePackage('mypy-boto3-qldb', 'QLDB', 179211),
  new ServicePackage('mypy-boto3-license-manager', 'LicenseManager', 179208),
  new ServicePackage('mypy-boto3-worklink', 'WorkLink', 179137),
  new ServicePackage('mypy-boto3-waf-regional', 'WAFRegional', 179092),
  new ServicePackage('mypy-boto3-machinelearning', 'MachineLearning', 179083),
  new ServicePackage('mypy-boto3-kinesis-video-media', 'KinesisVideoMedia', 179030),
  new ServicePackage('mypy-boto3-inspector', 'Inspector', 178936),
  new ServicePackage('mypy-boto3-ssm-contacts', 'SSMContacts', 178889),
  new ServicePackage('mypy-boto3-clouddirectory', 'CloudDirectory', 178855),
  new ServicePackage('mypy-boto3-cloudhsm', 'CloudHSM', 178854),
  new ServicePackage('mypy-boto3-discovery', 'ApplicationDiscoveryService', 178833),
  new ServicePackage('mypy-boto3-storagegateway', 'StorageGateway', 178715),
  new ServicePackage('mypy-boto3-fsx', 'FSx', 178671),
  new ServicePackage('mypy-boto3-cur', 'CostandUsageReportService', 178651),
  new ServicePackage('mypy-boto3-resource-groups', 'ResourceGroups', 178643),
  new ServicePackage('mypy-boto3-cognito-sync', 'CognitoSync', 178641),
  new ServicePackage('mypy-boto3-amp', 'PrometheusService', 178631),
  new ServicePackage('mypy-boto3-mediapackage-vod', 'MediaPackageVod', 178626),
  new ServicePackage('mypy-boto3-imagebuilder', 'Imagebuilder', 178610),
  new ServicePackage('mypy-boto3-iotevents', 'IoTEvents', 178582),
  new ServicePackage('mypy-boto3-iotfleetwise', 'IoTFleetWise', 178580),
  new ServicePackage('mypy-boto3-workdocs', 'WorkDocs', 178569),
  new ServicePackage('mypy-boto3-mq', 'MQ', 178547),
  new ServicePackage('mypy-boto3-devicefarm', 'DeviceFarm', 178542),
  new ServicePackage('mypy-boto3-application-insights', 'ApplicationInsights', 178504),
  new ServicePackage('mypy-boto3-inspector2', 'Inspector2', 178496),
  new ServicePackage('mypy-boto3-marketplace-catalog', 'MarketplaceCatalog', 178439),
  new ServicePackage('mypy-boto3-fms', 'FMS', 178396),
  new ServicePackage('mypy-boto3-keyspaces', 'Keyspaces', 178392),
  new ServicePackage('mypy-boto3-ivs', 'IVS', 178341),
  new ServicePackage('mypy-boto3-elastictranscoder', 'ElasticTranscoder', 178337),
  new ServicePackage('mypy-boto3-gamelift', 'GameLift', 178334),
  new ServicePackage('mypy-boto3-workmailmessageflow', 'WorkMailMessageFlow', 178332),
  new ServicePackage('mypy-boto3-globalaccelerator', 'GlobalAccelerator', 178319),
  new ServicePackage('mypy-boto3-kinesisvideo', 'KinesisVideo', 178262),
  new ServicePackage('mypy-boto3-mturk', 'MTurk', 178258),
  new ServicePackage('mypy-boto3-osis', 'OpenSearchIngestion', 178215),
  new ServicePackage(
    'mypy-boto3-sagemaker-featurestore-runtime',
    'SageMakerFeatureStoreRuntime',
    178193
  ),
  new ServicePackage('mypy-boto3-braket', 'Braket', 178158),
  new ServicePackage('mypy-boto3-appintegrations', 'AppIntegrationsService', 178147),
  new ServicePackage('mypy-boto3-lightsail', 'Lightsail', 178146),
  new ServicePackage('mypy-boto3-medialive', 'MediaLive', 178138),
  new ServicePackage('mypy-boto3-kinesisanalyticsv2', 'KinesisAnalyticsV2', 178119),
  new ServicePackage('mypy-boto3-forecastquery', 'ForecastQueryService', 178079),
  new ServicePackage('mypy-boto3-snowball', 'Snowball', 178040),
  new ServicePackage('mypy-boto3-health', 'Health', 178029),
  new ServicePackage('mypy-boto3-codestar', 'CodeStar', 178022),
  new ServicePackage('mypy-boto3-waf', 'WAF', 178019),
  new ServicePackage('mypy-boto3-mediapackage', 'MediaPackage', 177967),
  new ServicePackage('mypy-boto3-opsworkscm', 'OpsWorksCM', 177959),
  new ServicePackage(
    'mypy-boto3-marketplacecommerceanalytics',
    'MarketplaceCommerceAnalytics',
    177908
  ),
  new ServicePackage('mypy-boto3-cleanrooms', 'CleanRoomsService', 177897),
  new ServicePackage('mypy-boto3-opsworks', 'OpsWorks', 177867),
  new ServicePackage('mypy-boto3-iotwireless', 'IoTWireless', 177850),
  new ServicePackage('mypy-boto3-detective', 'Detective', 177835),
  new ServicePackage('mypy-boto3-wellarchitected', 'WellArchitected', 177835),
  new ServicePackage('mypy-boto3-cloudcontrol', 'CloudControlApi', 177820),
  new ServicePackage('mypy-boto3-outposts', 'Outposts', 177819),
  new ServicePackage('mypy-boto3-iotsecuretunneling', 'IoTSecureTunneling', 177818),
  new ServicePackage('mypy-boto3-ivschat', 'Ivschat', 177801),
  new ServicePackage('mypy-boto3-lookoutvision', 'LookoutforVision', 177752),
  new ServicePackage('mypy-boto3-apprunner', 'AppRunner', 177725),
  new ServicePackage('mypy-boto3-workspaces-web', 'WorkSpacesWeb', 177710),
  new ServicePackage('mypy-boto3-groundstation', 'GroundStation', 177689),
  new ServicePackage('mypy-boto3-cloudhsmv2', 'CloudHSMV2', 177670),
  new ServicePackage(
    'mypy-boto3-route53-recovery-control-config',
    'Route53RecoveryControlConfig',
    177668
  ),
  new ServicePackage('mypy-boto3-frauddetector', 'FraudDetector', 177659),
  new ServicePackage('mypy-boto3-amplifybackend', 'AmplifyBackend', 177658),
  new ServicePackage('mypy-boto3-auditmanager', 'AuditManager', 177630),
  new ServicePackage('mypy-boto3-importexport', 'ImportExport', 177625),
  new ServicePackage('mypy-boto3-kendra', 'Kendra', 177592),
  new ServicePackage('mypy-boto3-autoscaling-plans', 'AutoScalingPlans', 177581),
  new ServicePackage('mypy-boto3-forecast', 'ForecastService', 177512),
  new ServicePackage('mypy-boto3-healthlake', 'HealthLake', 177502),
  new ServicePackage('mypy-boto3-codeguruprofiler', 'CodeGuruProfiler', 177495),
  new ServicePackage('mypy-boto3-migrationhub-config', 'MigrationHubConfig', 177494),
  new ServicePackage('mypy-boto3-elastic-inference', 'ElasticInference', 177471),
  new ServicePackage('mypy-boto3-lexv2-runtime', 'LexRuntimeV2', 177470),
  new ServicePackage('mypy-boto3-iotdeviceadvisor', 'IoTDeviceAdvisor', 177467),
  new ServicePackage('mypy-boto3-codestar-connections', 'CodeStarconnections', 177457),
  new ServicePackage('mypy-boto3-mediaconnect', 'MediaConnect', 177449),
  new ServicePackage('mypy-boto3-datapipeline', 'DataPipeline', 177434),
  new ServicePackage('mypy-boto3-mediatailor', 'MediaTailor', 177422),
  new ServicePackage('mypy-boto3-iotanalytics', 'IoTAnalytics', 177385),
  new ServicePackage('mypy-boto3-controltower', 'ControlTower', 177359),
  new ServicePackage('mypy-boto3-connectparticipant', 'ConnectParticipant', 177358),
  new ServicePackage('mypy-boto3-launch-wizard', 'LaunchWizard', 177356),
  new ServicePackage('mypy-boto3-connect-contact-lens', 'ConnectContactLens', 177348),
  new ServicePackage('mypy-boto3-iot1click-devices', 'IoT1ClickDevicesService', 177321),
  new ServicePackage('mypy-boto3-dax', 'DAX', 177316),
  new ServicePackage(
    'mypy-boto3-kinesis-video-archived-media',
    'KinesisVideoArchivedMedia',
    177302
  ),
  new ServicePackage('mypy-boto3-docdb-elastic', 'DocDBElastic', 177298),
  new ServicePackage('mypy-boto3-codeguru-reviewer', 'CodeGuruReviewer', 177274),
  new ServicePackage('mypy-boto3-greengrass', 'Greengrass', 177264),
  new ServicePackage('mypy-boto3-iotevents-data', 'IoTEventsData', 177262),
  new ServicePackage(
    'mypy-boto3-migrationhubstrategy',
    'MigrationHubStrategyRecommendations',
    177249
  ),
  new ServicePackage('mypy-boto3-workspaces-thin-client', 'WorkSpacesThinClient', 177234),
  new ServicePackage('mypy-boto3-simspaceweaver', 'SimSpaceWeaver', 177228),
  new ServicePackage('mypy-boto3-cloud9', 'Cloud9', 177220),
  new ServicePackage('mypy-boto3-mediastore-data', 'MediaStoreData', 177195),
  new ServicePackage('mypy-boto3-devops-guru', 'DevOpsGuru', 177194),
  new ServicePackage('mypy-boto3-connectcases', 'ConnectCases', 177193),
  new ServicePackage('mypy-boto3-backupstorage', 'BackupStorage', 177186),
  new ServicePackage('mypy-boto3-customer-profiles', 'CustomerProfiles', 177186),
  new ServicePackage('mypy-boto3-proton', 'Proton', 177178),
  new ServicePackage('mypy-boto3-vpc-lattice', 'VPCLattice', 177173),
  new ServicePackage('mypy-boto3-voice-id', 'VoiceID', 177171),
  new ServicePackage('mypy-boto3-qldb-session', 'QLDBSession', 177159),
  new ServicePackage('mypy-boto3-wisdom', 'ConnectWisdomService', 177138),
  new ServicePackage('mypy-boto3-applicationcostprofiler', 'ApplicationCostProfiler', 177133),
  new ServicePackage('mypy-boto3-kinesisanalytics', 'KinesisAnalytics', 177124),
  new ServicePackage('mypy-boto3-sagemaker-metrics', 'SageMakerMetrics', 177108),
  new ServicePackage('mypy-boto3-amplifyuibuilder', 'AmplifyUIBuilder', 177052),
  new ServicePackage('mypy-boto3-sms', 'SMS', 177052),
  new ServicePackage('mypy-boto3-iot1click-projects', 'IoT1ClickProjects', 177047),
  new ServicePackage('mypy-boto3-macie2', 'Macie2', 177035),
  new ServicePackage('mypy-boto3-fis', 'FIS', 177010),
  new ServicePackage('mypy-boto3-chime-sdk-messaging', 'ChimeSDKMessaging', 176996),
  new ServicePackage('mypy-boto3-iotfleethub', 'IoTFleetHub', 176992),
  new ServicePackage('mypy-boto3-verifiedpermissions', 'VerifiedPermissions', 176987),
  new ServicePackage('mypy-boto3-iotthingsgraph', 'IoTThingsGraph', 176973),
  new ServicePackage('mypy-boto3-personalize-runtime', 'PersonalizeRuntime', 176962),
  new ServicePackage('mypy-boto3-kafkaconnect', 'KafkaConnect', 176920),
  new ServicePackage('mypy-boto3-sagemaker-a2i-runtime', 'AugmentedAIRuntime', 176895),
  new ServicePackage('mypy-boto3-lex-models', 'LexModelBuildingService', 176891),
  new ServicePackage('mypy-boto3-support-app', 'SupportApp', 176881),
  new ServicePackage('mypy-boto3-iotsitewise', 'IoTSiteWise', 176858),
  new ServicePackage('mypy-boto3-mgh', 'MigrationHub', 176851),
  new ServicePackage('mypy-boto3-lexv2-models', 'LexModelsV2', 176849),
  new ServicePackage('mypy-boto3-sms-voice', 'PinpointSMSVoice', 176843),
  new ServicePackage('mypy-boto3-arc-zonal-shift', 'ARCZonalShift', 176839),
  new ServicePackage('mypy-boto3-b2bi', 'B2BI', 176823),
  new ServicePackage('mypy-boto3-backup-gateway', 'BackupGateway', 176810),
  new ServicePackage('mypy-boto3-personalize-events', 'PersonalizeEvents', 176804),
  new ServicePackage('mypy-boto3-lex-runtime', 'LexRuntimeService', 176774),
  new ServicePackage('mypy-boto3-iot-jobs-data', 'IoTJobsDataPlane', 176747),
  new ServicePackage('mypy-boto3-chime-sdk-media-pipelines', 'ChimeSDKMediaPipelines', 176731),
  new ServicePackage('mypy-boto3-savingsplans', 'SavingsPlans', 176718),
  new ServicePackage('mypy-boto3-chime-sdk-meetings', 'ChimeSDKMeetings', 176707),
  new ServicePackage('mypy-boto3-cleanroomsml', 'CleanRoomsML', 176665),
  new ServicePackage('mypy-boto3-sagemaker-edge', 'SagemakerEdgeManager', 176647),
  new ServicePackage('mypy-boto3-kinesis-video-signaling', 'KinesisVideoSignalingChannels', 176587),
  new ServicePackage('mypy-boto3-pinpoint-sms-voice', 'PinpointSMSVoice', 176574),
  new ServicePackage('mypy-boto3-route53domains', 'Route53Domains', 176574),
  new ServicePackage('mypy-boto3-payment-cryptography', 'PaymentCryptographyControlPlane', 176568),
  new ServicePackage('mypy-boto3-finspace', 'Finspace', 176555),
  new ServicePackage('mypy-boto3-kendra-ranking', 'KendraRanking', 176548),
  new ServicePackage('mypy-boto3-chime-sdk-identity', 'ChimeSDKIdentity', 176544),
  new ServicePackage('mypy-boto3-medical-imaging', 'HealthImaging', 176530),
  new ServicePackage('mypy-boto3-billingconductor', 'BillingConductor', 176526),
  new ServicePackage('mypy-boto3-robomaker', 'RoboMaker', 176518),
  new ServicePackage('mypy-boto3-chime-sdk-voice', 'ChimeSDKVoice', 176500),
  new ServicePackage('mypy-boto3-panorama', 'Panorama', 176495),
  new ServicePackage('mypy-boto3-drs', 'Drs', 176486),
  new ServicePackage('mypy-boto3-lookoutequipment', 'LookoutEquipment', 176453),
  new ServicePackage('mypy-boto3-nimble', 'NimbleStudio', 176362),
  new ServicePackage('mypy-boto3-resiliencehub', 'ResilienceHub', 176327),
  new ServicePackage('mypy-boto3-mobile', 'Mobile', 176278),
  new ServicePackage('mypy-boto3-s3outposts', 'S3Outposts', 176264),
  new ServicePackage('mypy-boto3-finspace-data', 'FinSpaceData', 176212),
  new ServicePackage('mypy-boto3-mgn', 'Mgn', 176184),
  new ServicePackage('mypy-boto3-rolesanywhere', 'IAMRolesAnywhere', 176156),
  new ServicePackage('mypy-boto3-connectcampaigns', 'ConnectCampaignService', 176141),
  new ServicePackage('mypy-boto3-appfabric', 'AppFabric', 176132),
  new ServicePackage('mypy-boto3-snow-device-management', 'SnowDeviceManagement', 176110),
  new ServicePackage('mypy-boto3-tnb', 'TelcoNetworkBuilder', 176067),
  new ServicePackage('mypy-boto3-iottwinmaker', 'IoTTwinMaker', 176056),
  new ServicePackage('mypy-boto3-evidently', 'CloudWatchEvidently', 176017),
  new ServicePackage('mypy-boto3-cloudtrail-data', 'CloudTrailDataService', 175941),
  new ServicePackage('mypy-boto3-trustedadvisor', 'TrustedAdvisorPublicAPI', 175927),
  new ServicePackage('mypy-boto3-lookoutmetrics', 'LookoutMetrics', 175917),
  new ServicePackage('mypy-boto3-codecatalyst', 'CodeCatalyst', 175914),
  new ServicePackage('mypy-boto3-bcm-data-exports', 'BillingandCostManagementDataExports', 175884),
  new ServicePackage('mypy-boto3-omics', 'Omics', 175873),
  new ServicePackage('mypy-boto3-servicecatalog-appregistry', 'AppRegistry', 175872),
  new ServicePackage('mypy-boto3-pinpoint-sms-voice-v2', 'PinpointSMSVoiceV2', 175867),
  new ServicePackage('mypy-boto3-codeguru-security', 'CodeGuruSecurity', 175812),
  new ServicePackage('mypy-boto3-eks-auth', 'EKSAuth', 175795),
  new ServicePackage('mypy-boto3-memorydb', 'MemoryDB', 175788),
  new ServicePackage('mypy-boto3-rum', 'CloudWatchRUM', 175701),
  new ServicePackage('mypy-boto3-route53-recovery-cluster', 'Route53RecoveryCluster', 175700),
  new ServicePackage('mypy-boto3-route53-recovery-readiness', 'Route53RecoveryReadiness', 175651),
  new ServicePackage('mypy-boto3-qbusiness', 'QBusiness', 175637),
  new ServicePackage(
    'mypy-boto3-license-manager-user-subscriptions',
    'LicenseManagerUserSubscriptions',
    175564
  ),
  new ServicePackage('mypy-boto3-pipes', 'EventBridgePipes', 175546),
  new ServicePackage('mypy-boto3-m2', 'MainframeModernization', 175545),
  new ServicePackage('mypy-boto3-ivs-realtime', 'Ivsrealtime', 175539),
  new ServicePackage('mypy-boto3-cloudfront-keyvaluestore', 'CloudFrontKeyValueStore', 175529),
  new ServicePackage('mypy-boto3-internetmonitor', 'CloudWatchInternetMonitor', 175513),
  new ServicePackage(
    'mypy-boto3-kinesis-video-webrtc-storage',
    'KinesisVideoWebRTCStorage',
    175503
  ),
  new ServicePackage('mypy-boto3-entityresolution', 'EntityResolution', 175473),
  new ServicePackage('mypy-boto3-rbin', 'RecycleBin', 175456),
  new ServicePackage(
    'mypy-boto3-migration-hub-refactor-spaces',
    'MigrationHubRefactorSpaces',
    175453
  ),
  new ServicePackage('mypy-boto3-privatenetworks', 'Private5G', 175397),
  new ServicePackage('mypy-boto3-cost-optimization-hub', 'CostOptimizationHub', 175395),
  new ServicePackage('mypy-boto3-marketplace-agreement', 'AgreementService', 175394),
  new ServicePackage('mypy-boto3-datazone', 'DataZone', 175377),
  new ServicePackage('mypy-boto3-oam', 'CloudWatchObservabilityAccessManager', 175349),
  new ServicePackage('mypy-boto3-marketplace-deployment', 'MarketplaceDeploymentService', 175265),
  new ServicePackage('mypy-boto3-migrationhuborchestrator', 'MigrationHubOrchestrator', 175263),
  new ServicePackage(
    'mypy-boto3-license-manager-linux-subscriptions',
    'LicenseManagerLinuxSubscriptions',
    175257
  ),
  new ServicePackage('mypy-boto3-securitylake', 'SecurityLake', 175200),
  new ServicePackage('mypy-boto3-sagemaker-geospatial', 'SageMakergeospatialcapabilities', 175190),
  new ServicePackage('mypy-boto3-freetier', 'FreeTier', 175073),
  new ServicePackage('mypy-boto3-resource-explorer-2', 'ResourceExplorer', 175064),
  new ServicePackage('mypy-boto3-inspector-scan', 'Inspectorscan', 174970),
  new ServicePackage('mypy-boto3-managedblockchain-query', 'ManagedBlockchainQuery', 174961),
  new ServicePackage(
    'mypy-boto3-payment-cryptography-data',
    'PaymentCryptographyDataPlane',
    174862
  ),
  new ServicePackage('mypy-boto3-pca-connector-ad', 'PcaConnectorAd', 174771),
  new ServicePackage('mypy-boto3-qconnect', 'QConnect', 174761),
  new ServicePackage('mypy-boto3-mediapackagev2', 'Mediapackagev2', 174702),
  new ServicePackage('mypy-boto3-supplychain', 'SupplyChain', 174495),
  new ServicePackage('mypy-boto3-repostspace', 'RePostPrivate', 174481),
  new ServicePackage('mypy-boto3-neptune-graph', 'NeptuneGraph', 174295),
  new ServicePackage('mypy-boto3-networkmonitor', 'CloudWatchNetworkMonitor', 174259),
  new ServicePackage('mypy-boto3-chatbot', 'Chatbot', 174193),
  new ServicePackage('mypy-boto3-artifact', 'Artifact', 173242),
  new ServicePackage('mypy-boto3-timestream-influxdb', 'TimestreamInfluxDB', 171873),
  new ServicePackage('mypy-boto3-codeconnections', 'CodeConnections', 171846),
  new ServicePackage('mypy-boto3-route53profiles', 'Route53Profiles', 171675),
  new ServicePackage('mypy-boto3-controlcatalog', 'ControlCatalog', 171666),
  new ServicePackage('mypy-boto3-deadline', 'DeadlineCloud', 171425),
  new ServicePackage('mypy-boto3-mailmanager', 'MailManager', 100646),
  new ServicePackage('mypy-boto3-taxsettings', 'TaxSettings', 1283)
]
