import { ServicePackage } from './servicePackage'

export const servicePackages: ServicePackage[] = [
  new ServicePackage('mypy-boto3-rds', 'RDS', 10346449),
  new ServicePackage('mypy-boto3-s3', 'S3', 7505932),
  new ServicePackage('mypy-boto3-appflow', 'Appflow', 6248785),
  new ServicePackage('mypy-boto3-redshift-data', 'RedshiftDataAPIService', 4185003),
  new ServicePackage('mypy-boto3-secretsmanager', 'SecretsManager', 2487816),
  new ServicePackage('mypy-boto3-dynamodb', 'DynamoDB', 2477070),
  new ServicePackage('mypy-boto3-glue', 'Glue', 2429872),
  new ServicePackage('mypy-boto3-sqs', 'SQS', 2427789),
  new ServicePackage('mypy-boto3-lambda', 'Lambda', 2368081),
  new ServicePackage('mypy-boto3-cloudformation', 'CloudFormation', 1972301),
  new ServicePackage('mypy-boto3-ec2', 'EC2', 1884750),
  new ServicePackage('mypy-boto3-sts', 'STS', 1583171),
  new ServicePackage('mypy-boto3-athena', 'Athena', 1150795),
  new ServicePackage('mypy-boto3-iam', 'IAM', 1064148),
  new ServicePackage('mypy-boto3-kinesis', 'Kinesis', 994624),
  new ServicePackage('mypy-boto3-stepfunctions', 'SFN', 908719),
  new ServicePackage('mypy-boto3-ecr', 'ECR', 907385),
  new ServicePackage('mypy-boto3-apigateway', 'APIGateway', 841812),
  new ServicePackage('mypy-boto3-ssm', 'SSM', 790138),
  new ServicePackage('mypy-boto3-xray', 'XRay', 786891),
  new ServicePackage('mypy-boto3-schemas', 'Schemas', 781903),
  new ServicePackage('mypy-boto3-signer', 'Signer', 780980),
  new ServicePackage('mypy-boto3-appconfig', 'AppConfig', 712891),
  new ServicePackage('mypy-boto3-events', 'EventBridge', 630008),
  new ServicePackage('mypy-boto3-kms', 'KMS', 509326),
  new ServicePackage('mypy-boto3-elbv2', 'ElasticLoadBalancingv2', 486231),
  new ServicePackage('mypy-boto3-sns', 'SNS', 469766),
  new ServicePackage('mypy-boto3-cloudwatch', 'CloudWatch', 377250),
  new ServicePackage('mypy-boto3-sso', 'SSO', 367539),
  new ServicePackage('mypy-boto3-ses', 'SES', 335011),
  new ServicePackage('mypy-boto3-logs', 'CloudWatchLogs', 327965),
  new ServicePackage('mypy-boto3-eks', 'EKS', 320958),
  new ServicePackage('mypy-boto3-servicecatalog', 'ServiceCatalog', 316728),
  new ServicePackage('mypy-boto3-route53', 'Route53', 300847),
  new ServicePackage('mypy-boto3-ecs', 'ECS', 299440),
  new ServicePackage('mypy-boto3-cognito-idp', 'CognitoIdentityProvider', 296742),
  new ServicePackage('mypy-boto3-sagemaker', 'SageMaker', 294938),
  new ServicePackage('mypy-boto3-firehose', 'Firehose', 277451),
  new ServicePackage('mypy-boto3-batch', 'Batch', 272942),
  new ServicePackage('mypy-boto3-lakeformation', 'LakeFormation', 269409),
  new ServicePackage('mypy-boto3-emr', 'EMR', 267881),
  new ServicePackage('mypy-boto3-autoscaling', 'AutoScaling', 253710),
  new ServicePackage('mypy-boto3-sagemaker-runtime', 'SageMakerRuntime', 242456),
  new ServicePackage('mypy-boto3-dms', 'DatabaseMigrationService', 219225),
  new ServicePackage('mypy-boto3-cognito-identity', 'CognitoIdentity', 216352),
  new ServicePackage('mypy-boto3-textract', 'Textract', 213615),
  new ServicePackage('mypy-boto3-cloudfront', 'CloudFront', 212139),
  new ServicePackage('mypy-boto3-cloudtrail', 'CloudTrail', 210585),
  new ServicePackage('mypy-boto3-acm', 'ACM', 205939),
  new ServicePackage('mypy-boto3-ce', 'CostExplorer', 203989),
  new ServicePackage('mypy-boto3-wafv2', 'WAFV2', 201355),
  new ServicePackage('mypy-boto3-organizations', 'Organizations', 201317),
  new ServicePackage('mypy-boto3-resourcegroupstaggingapi', 'ResourceGroupsTaggingAPI', 200504),
  new ServicePackage('mypy-boto3-efs', 'EFS', 197954),
  new ServicePackage('mypy-boto3-opensearch', 'OpenSearchService', 197047),
  new ServicePackage('mypy-boto3-codepipeline', 'CodePipeline', 194711),
  new ServicePackage('mypy-boto3-es', 'ElasticsearchService', 193734),
  new ServicePackage('mypy-boto3-elasticache', 'ElastiCache', 193290),
  new ServicePackage('mypy-boto3-quicksight', 'QuickSight', 189323),
  new ServicePackage('mypy-boto3-config', 'ConfigService', 186856),
  new ServicePackage('mypy-boto3-iot', 'IoT', 184834),
  new ServicePackage('mypy-boto3-guardduty', 'GuardDuty', 183921),
  new ServicePackage('mypy-boto3-transfer', 'Transfer', 183631),
  new ServicePackage('mypy-boto3-sesv2', 'SESV2', 183628),
  new ServicePackage('mypy-boto3-securityhub', 'SecurityHub', 182744),
  new ServicePackage('mypy-boto3-codebuild', 'CodeBuild', 182735),
  new ServicePackage('mypy-boto3-dynamodbstreams', 'DynamoDBStreams', 182389),
  new ServicePackage('mypy-boto3-accessanalyzer', 'AccessAnalyzer', 182373),
  new ServicePackage('mypy-boto3-kafka', 'Kafka', 181606),
  new ServicePackage('mypy-boto3-identitystore', 'IdentityStore', 180669),
  new ServicePackage('mypy-boto3-transcribe', 'TranscribeService', 179551),
  new ServicePackage('mypy-boto3-mwaa', 'MWAA', 179465),
  new ServicePackage('mypy-boto3-codedeploy', 'CodeDeploy', 178809),
  new ServicePackage('mypy-boto3-redshift', 'Redshift', 178619),
  new ServicePackage('mypy-boto3-translate', 'Translate', 178267),
  new ServicePackage('mypy-boto3-service-quotas', 'ServiceQuotas', 177858),
  new ServicePackage('mypy-boto3-application-autoscaling', 'ApplicationAutoScaling', 177173),
  new ServicePackage('mypy-boto3-rds-data', 'RDSDataService', 176973),
  new ServicePackage('mypy-boto3-synthetics', 'Synthetics', 176968),
  new ServicePackage('mypy-boto3-pinpoint', 'Pinpoint', 176929),
  new ServicePackage('mypy-boto3-apigatewaymanagementapi', 'ApiGatewayManagementApi', 176796),
  new ServicePackage('mypy-boto3-network-firewall', 'NetworkFirewall', 176309),
  new ServicePackage('mypy-boto3-location', 'LocationService', 175981),
  new ServicePackage('mypy-boto3-ec2-instance-connect', 'EC2InstanceConnect', 175937),
  new ServicePackage('mypy-boto3-ebs', 'EBS', 175871),
  new ServicePackage('mypy-boto3-marketplace-entitlement', 'MarketplaceEntitlementService', 175871),
  new ServicePackage('mypy-boto3-codeartifact', 'CodeArtifact', 175270),
  new ServicePackage('mypy-boto3-dlm', 'DLM', 174529),
  new ServicePackage('mypy-boto3-budgets', 'Budgets', 173927),
  new ServicePackage('mypy-boto3-iot-data', 'IoTDataPlane', 173868),
  new ServicePackage('mypy-boto3-apigatewayv2', 'ApiGatewayV2', 173642),
  new ServicePackage('mypy-boto3-mediaconvert', 'MediaConvert', 173499),
  new ServicePackage('mypy-boto3-elb', 'ElasticLoadBalancing', 173418),
  new ServicePackage('mypy-boto3-support', 'Support', 173091),
  new ServicePackage('mypy-boto3-appsync', 'AppSync', 171907),
  new ServicePackage('mypy-boto3-bedrock', 'Bedrock', 171831),
  new ServicePackage('mypy-boto3-emr-containers', 'EMRContainers', 170761),
  new ServicePackage('mypy-boto3-cloudsearchdomain', 'CloudSearchDomain', 170334),
  new ServicePackage('mypy-boto3-backup', 'Backup', 170270),
  new ServicePackage('mypy-boto3-rekognition', 'Rekognition', 169995),
  new ServicePackage('mypy-boto3-cloudsearch', 'CloudSearch', 169389),
  new ServicePackage('mypy-boto3-ram', 'RAM', 168822),
  new ServicePackage('mypy-boto3-timestream-write', 'TimestreamWrite', 168368),
  new ServicePackage('mypy-boto3-imagebuilder', 'Imagebuilder', 168264),
  new ServicePackage('mypy-boto3-amplify', 'Amplify', 168107),
  new ServicePackage('mypy-boto3-codecommit', 'CodeCommit', 168102),
  new ServicePackage('mypy-boto3-sdb', 'SimpleDB', 167682),
  new ServicePackage('mypy-boto3-acm-pca', 'ACMPCA', 167311),
  new ServicePackage('mypy-boto3-scheduler', 'EventBridgeScheduler', 166869),
  new ServicePackage('mypy-boto3-timestream-query', 'TimestreamQuery', 166697),
  new ServicePackage('mypy-boto3-workspaces', 'WorkSpaces', 166543),
  new ServicePackage('mypy-boto3-comprehend', 'Comprehend', 165358),
  new ServicePackage('mypy-boto3-bedrock-runtime', 'BedrockRuntime', 165354),
  new ServicePackage('mypy-boto3-polly', 'Polly', 164885),
  new ServicePackage('mypy-boto3-route53resolver', 'Route53Resolver', 164189),
  new ServicePackage('mypy-boto3-serverlessrepo', 'ServerlessApplicationRepository', 163897),
  new ServicePackage('mypy-boto3-glacier', 'Glacier', 162425),
  new ServicePackage('mypy-boto3-docdb', 'DocDB', 162399),
  new ServicePackage('mypy-boto3-ecr-public', 'ECRPublic', 161762),
  new ServicePackage('mypy-boto3-meteringmarketplace', 'MarketplaceMetering', 157246),
  new ServicePackage('mypy-boto3-databrew', 'GlueDataBrew', 156580),
  new ServicePackage('mypy-boto3-servicediscovery', 'ServiceDiscovery', 156522),
  new ServicePackage('mypy-boto3-neptunedata', 'NeptuneData', 156245),
  new ServicePackage('mypy-boto3-qldb', 'QLDB', 155935),
  new ServicePackage('mypy-boto3-connect', 'Connect', 155504),
  new ServicePackage('mypy-boto3-shield', 'Shield', 155066),
  new ServicePackage('mypy-boto3-appmesh', 'AppMesh', 154931),
  new ServicePackage('mypy-boto3-s3control', 'S3Control', 154779),
  new ServicePackage('mypy-boto3-emr-serverless', 'EMRServerless', 154674),
  new ServicePackage('mypy-boto3-bedrock-agent', 'AgentsforBedrock', 154532),
  new ServicePackage('mypy-boto3-datasync', 'DataSync', 154519),
  new ServicePackage('mypy-boto3-iotwireless', 'IoTWireless', 154383),
  new ServicePackage('mypy-boto3-compute-optimizer', 'ComputeOptimizer', 154346),
  new ServicePackage('mypy-boto3-groundstation', 'GroundStation', 154248),
  new ServicePackage('mypy-boto3-pricing', 'Pricing', 154248),
  new ServicePackage('mypy-boto3-medialive', 'MediaLive', 153934),
  new ServicePackage('mypy-boto3-comprehendmedical', 'ComprehendMedical', 153700),
  new ServicePackage('mypy-boto3-ivs', 'IVS', 153419),
  new ServicePackage('mypy-boto3-resource-groups', 'ResourceGroups', 153256),
  new ServicePackage('mypy-boto3-sso-admin', 'SSOAdmin', 152864),
  new ServicePackage('mypy-boto3-kendra', 'Kendra', 152829),
  new ServicePackage('mypy-boto3-dataexchange', 'DataExchange', 152725),
  new ServicePackage('mypy-boto3-workmail', 'WorkMail', 152701),
  new ServicePackage('mypy-boto3-pi', 'PI', 152642),
  new ServicePackage(
    'mypy-boto3-marketplacecommerceanalytics',
    'MarketplaceCommerceAnalytics',
    152596
  ),
  new ServicePackage('mypy-boto3-neptune', 'Neptune', 152581),
  new ServicePackage('mypy-boto3-iotevents', 'IoTEvents', 152558),
  new ServicePackage('mypy-boto3-chime', 'Chime', 152532),
  new ServicePackage('mypy-boto3-kinesisanalyticsv2', 'KinesisAnalyticsV2', 152500),
  new ServicePackage('mypy-boto3-marketplace-catalog', 'MarketplaceCatalog', 152463),
  new ServicePackage('mypy-boto3-mediastore', 'MediaStore', 152428),
  new ServicePackage('mypy-boto3-managedblockchain', 'ManagedBlockchain', 152426),
  new ServicePackage('mypy-boto3-directconnect', 'DirectConnect', 152258),
  new ServicePackage('mypy-boto3-datapipeline', 'DataPipeline', 152200),
  new ServicePackage('mypy-boto3-codestar', 'CodeStar', 152130),
  new ServicePackage('mypy-boto3-greengrassv2', 'GreengrassV2', 152124),
  new ServicePackage('mypy-boto3-mediatailor', 'MediaTailor', 152122),
  new ServicePackage('mypy-boto3-appstream', 'AppStream', 152022),
  new ServicePackage('mypy-boto3-codeguru-reviewer', 'CodeGuruReviewer', 151999),
  new ServicePackage('mypy-boto3-inspector', 'Inspector', 151849),
  new ServicePackage('mypy-boto3-application-insights', 'ApplicationInsights', 151838),
  new ServicePackage('mypy-boto3-waf', 'WAF', 151834),
  new ServicePackage('mypy-boto3-mgh', 'MigrationHub', 151825),
  new ServicePackage('mypy-boto3-codestar-connections', 'CodeStarconnections', 151811),
  new ServicePackage('mypy-boto3-cloudhsm', 'CloudHSM', 151803),
  new ServicePackage('mypy-boto3-cloudhsmv2', 'CloudHSMV2', 151772),
  new ServicePackage('mypy-boto3-alexaforbusiness', 'AlexaForBusiness', 151757),
  new ServicePackage('mypy-boto3-mq', 'MQ', 151731),
  new ServicePackage('mypy-boto3-cognito-sync', 'CognitoSync', 151712),
  new ServicePackage('mypy-boto3-elastictranscoder', 'ElasticTranscoder', 151696),
  new ServicePackage('mypy-boto3-workdocs', 'WorkDocs', 151650),
  new ServicePackage('mypy-boto3-ds', 'DirectoryService', 151599),
  new ServicePackage('mypy-boto3-personalize-runtime', 'PersonalizeRuntime', 151584),
  new ServicePackage('mypy-boto3-autoscaling-plans', 'AutoScalingPlans', 151575),
  new ServicePackage('mypy-boto3-waf-regional', 'WAFRegional', 151563),
  new ServicePackage('mypy-boto3-mediapackage', 'MediaPackage', 151541),
  new ServicePackage('mypy-boto3-gamelift', 'GameLift', 151496),
  new ServicePackage('mypy-boto3-wellarchitected', 'WellArchitected', 151464),
  new ServicePackage('mypy-boto3-dax', 'DAX', 151463),
  new ServicePackage('mypy-boto3-sagemaker-a2i-runtime', 'AugmentedAIRuntime', 151455),
  new ServicePackage('mypy-boto3-workmailmessageflow', 'WorkMailMessageFlow', 151451),
  new ServicePackage('mypy-boto3-clouddirectory', 'CloudDirectory', 151413),
  new ServicePackage('mypy-boto3-codestar-notifications', 'CodeStarNotifications', 151393),
  new ServicePackage('mypy-boto3-grafana', 'ManagedGrafana', 151389),
  new ServicePackage('mypy-boto3-mediapackage-vod', 'MediaPackageVod', 151383),
  new ServicePackage('mypy-boto3-networkmanager', 'NetworkManager', 151350),
  new ServicePackage('mypy-boto3-kinesis-video-media', 'KinesisVideoMedia', 151273),
  new ServicePackage('mypy-boto3-worklink', 'WorkLink', 151256),
  new ServicePackage('mypy-boto3-elasticbeanstalk', 'ElasticBeanstalk', 151158),
  new ServicePackage('mypy-boto3-storagegateway', 'StorageGateway', 151095),
  new ServicePackage('mypy-boto3-healthlake', 'HealthLake', 151005),
  new ServicePackage('mypy-boto3-lex-models', 'LexModelBuildingService', 150983),
  new ServicePackage('mypy-boto3-lightsail', 'Lightsail', 150976),
  new ServicePackage('mypy-boto3-globalaccelerator', 'GlobalAccelerator', 150971),
  new ServicePackage('mypy-boto3-sso-oidc', 'SSOOIDC', 150925),
  new ServicePackage('mypy-boto3-mturk', 'MTurk', 150919),
  new ServicePackage('mypy-boto3-account', 'Account', 150910),
  new ServicePackage('mypy-boto3-cloud9', 'Cloud9', 150892),
  new ServicePackage('mypy-boto3-kinesisanalytics', 'KinesisAnalytics', 150864),
  new ServicePackage('mypy-boto3-fsx', 'FSx', 150852),
  new ServicePackage('mypy-boto3-discovery', 'ApplicationDiscoveryService', 150849),
  new ServicePackage('mypy-boto3-detective', 'Detective', 150848),
  new ServicePackage('mypy-boto3-opsworkscm', 'OpsWorksCM', 150846),
  new ServicePackage('mypy-boto3-cur', 'CostandUsageReportService', 150836),
  new ServicePackage('mypy-boto3-mediaconnect', 'MediaConnect', 150833),
  new ServicePackage('mypy-boto3-devicefarm', 'DeviceFarm', 150812),
  new ServicePackage('mypy-boto3-appconfigdata', 'AppConfigData', 150763),
  new ServicePackage('mypy-boto3-amp', 'PrometheusService', 150718),
  new ServicePackage('mypy-boto3-snowball', 'Snowball', 150706),
  new ServicePackage('mypy-boto3-robomaker', 'RoboMaker', 150705),
  new ServicePackage('mypy-boto3-iotsecuretunneling', 'IoTSecureTunneling', 150662),
  new ServicePackage('mypy-boto3-pinpoint-email', 'PinpointEmail', 150588),
  new ServicePackage(
    'mypy-boto3-kinesis-video-archived-media',
    'KinesisVideoArchivedMedia',
    150558
  ),
  new ServicePackage('mypy-boto3-greengrass', 'Greengrass', 150539),
  new ServicePackage('mypy-boto3-kinesis-video-signaling', 'KinesisVideoSignalingChannels', 150505),
  new ServicePackage('mypy-boto3-migrationhub-config', 'MigrationHubConfig', 150493),
  new ServicePackage('mypy-boto3-iotsitewise', 'IoTSiteWise', 150491),
  new ServicePackage('mypy-boto3-connectparticipant', 'ConnectParticipant', 150486),
  new ServicePackage('mypy-boto3-fms', 'FMS', 150373),
  new ServicePackage('mypy-boto3-kinesisvideo', 'KinesisVideo', 150359),
  new ServicePackage('mypy-boto3-iotdeviceadvisor', 'IoTDeviceAdvisor', 150221),
  new ServicePackage('mypy-boto3-opensearchserverless', 'OpenSearchServiceServerless', 150181),
  new ServicePackage('mypy-boto3-outposts', 'Outposts', 150175),
  new ServicePackage('mypy-boto3-elastic-inference', 'ElasticInference', 150072),
  new ServicePackage('mypy-boto3-amplifybackend', 'AmplifyBackend', 150067),
  new ServicePackage('mypy-boto3-sms-voice', 'PinpointSMSVoice', 149946),
  new ServicePackage('mypy-boto3-auditmanager', 'AuditManager', 149942),
  new ServicePackage('mypy-boto3-redshift-serverless', 'RedshiftServerless', 149918),
  new ServicePackage('mypy-boto3-iot1click-devices', 'IoT1ClickDevicesService', 149907),
  new ServicePackage('mypy-boto3-mobile', 'Mobile', 149824),
  new ServicePackage(
    'mypy-boto3-sagemaker-featurestore-runtime',
    'SageMakerFeatureStoreRuntime',
    149824
  ),
  new ServicePackage('mypy-boto3-braket', 'Braket', 149815),
  new ServicePackage('mypy-boto3-personalize', 'Personalize', 149749),
  new ServicePackage('mypy-boto3-forecast', 'ForecastService', 149746),
  new ServicePackage('mypy-boto3-cleanrooms', 'CleanRoomsService', 149706),
  new ServicePackage('mypy-boto3-iotfleethub', 'IoTFleetHub', 149683),
  new ServicePackage('mypy-boto3-lookoutvision', 'LookoutforVision', 149682),
  new ServicePackage('mypy-boto3-forecastquery', 'ForecastQueryService', 149601),
  new ServicePackage('mypy-boto3-machinelearning', 'MachineLearning', 149579),
  new ServicePackage('mypy-boto3-mgn', 'Mgn', 149510),
  new ServicePackage('mypy-boto3-license-manager', 'LicenseManager', 149496),
  new ServicePackage('mypy-boto3-savingsplans', 'SavingsPlans', 149425),
  new ServicePackage('mypy-boto3-lexv2-runtime', 'LexRuntimeV2', 149393),
  new ServicePackage('mypy-boto3-opsworks', 'OpsWorks', 149364),
  new ServicePackage('mypy-boto3-kafkaconnect', 'KafkaConnect', 149287),
  new ServicePackage('mypy-boto3-lookoutequipment', 'LookoutEquipment', 149254),
  new ServicePackage('mypy-boto3-swf', 'SWF', 149235),
  new ServicePackage('mypy-boto3-ssm-incidents', 'SSMIncidents', 149204),
  new ServicePackage('mypy-boto3-codeguruprofiler', 'CodeGuruProfiler', 149122),
  new ServicePackage('mypy-boto3-iotanalytics', 'IoTAnalytics', 149053),
  new ServicePackage('mypy-boto3-rolesanywhere', 'IAMRolesAnywhere', 149032),
  new ServicePackage('mypy-boto3-sagemaker-edge', 'SagemakerEdgeManager', 149004),
  new ServicePackage('mypy-boto3-health', 'Health', 148963),
  new ServicePackage('mypy-boto3-qldb-session', 'QLDBSession', 148946),
  new ServicePackage('mypy-boto3-frauddetector', 'FraudDetector', 148914),
  new ServicePackage('mypy-boto3-keyspaces', 'Keyspaces', 148878),
  new ServicePackage('mypy-boto3-iotthingsgraph', 'IoTThingsGraph', 148854),
  new ServicePackage('mypy-boto3-iot1click-projects', 'IoT1ClickProjects', 148837),
  new ServicePackage('mypy-boto3-sms', 'SMS', 148771),
  new ServicePackage('mypy-boto3-ivschat', 'Ivschat', 148738),
  new ServicePackage('mypy-boto3-importexport', 'ImportExport', 148727),
  new ServicePackage('mypy-boto3-workspaces-thin-client', 'WorkSpacesThinClient', 148690),
  new ServicePackage('mypy-boto3-personalize-events', 'PersonalizeEvents', 148680),
  new ServicePackage('mypy-boto3-iot-jobs-data', 'IoTJobsDataPlane', 148653),
  new ServicePackage('mypy-boto3-pinpoint-sms-voice', 'PinpointSMSVoice', 148647),
  new ServicePackage('mypy-boto3-proton', 'Proton', 148618),
  new ServicePackage('mypy-boto3-lex-runtime', 'LexRuntimeService', 148607),
  new ServicePackage('mypy-boto3-iotevents-data', 'IoTEventsData', 148566),
  new ServicePackage('mypy-boto3-finspace', 'Finspace', 148548),
  new ServicePackage('mypy-boto3-mediastore-data', 'MediaStoreData', 148534),
  new ServicePackage('mypy-boto3-route53domains', 'Route53Domains', 148458),
  new ServicePackage('mypy-boto3-appintegrations', 'AppIntegrationsService', 148364),
  new ServicePackage('mypy-boto3-customer-profiles', 'CustomerProfiles', 148266),
  new ServicePackage(
    'mypy-boto3-route53-recovery-control-config',
    'Route53RecoveryControlConfig',
    148222
  ),
  new ServicePackage('mypy-boto3-honeycode', 'Honeycode', 148202),
  new ServicePackage('mypy-boto3-macie2', 'Macie2', 148199),
  new ServicePackage('mypy-boto3-bedrock-agent-runtime', 'AgentsforBedrockRuntime', 148151),
  new ServicePackage('mypy-boto3-devops-guru', 'DevOpsGuru', 148120),
  new ServicePackage('mypy-boto3-wisdom', 'ConnectWisdomService', 148120),
  new ServicePackage('mypy-boto3-chime-sdk-messaging', 'ChimeSDKMessaging', 148098),
  new ServicePackage('mypy-boto3-cleanroomsml', 'CleanRoomsML', 148094),
  new ServicePackage('mypy-boto3-fis', 'FIS', 148056),
  new ServicePackage('mypy-boto3-workspaces-web', 'WorkSpacesWeb', 148052),
  new ServicePackage('mypy-boto3-lexv2-models', 'LexModelsV2', 148007),
  new ServicePackage('mypy-boto3-inspector2', 'Inspector2', 147990),
  new ServicePackage('mypy-boto3-applicationcostprofiler', 'ApplicationCostProfiler', 147786),
  new ServicePackage('mypy-boto3-connect-contact-lens', 'ConnectContactLens', 147779),
  new ServicePackage('mypy-boto3-apprunner', 'AppRunner', 147741),
  new ServicePackage('mypy-boto3-servicecatalog-appregistry', 'AppRegistry', 147717),
  new ServicePackage('mypy-boto3-verifiedpermissions', 'VerifiedPermissions', 147699),
  new ServicePackage('mypy-boto3-ssm-sap', 'SsmSap', 147661),
  new ServicePackage('mypy-boto3-b2bi', 'B2BI', 147653),
  new ServicePackage('mypy-boto3-cloudcontrol', 'CloudControlApi', 147629),
  new ServicePackage('mypy-boto3-codecatalyst', 'CodeCatalyst', 147504),
  new ServicePackage('mypy-boto3-snow-device-management', 'SnowDeviceManagement', 147477),
  new ServicePackage('mypy-boto3-chime-sdk-meetings', 'ChimeSDKMeetings', 147433),
  new ServicePackage(
    'mypy-boto3-migrationhubstrategy',
    'MigrationHubStrategyRecommendations',
    147409
  ),
  new ServicePackage('mypy-boto3-docdb-elastic', 'DocDBElastic', 147397),
  new ServicePackage('mypy-boto3-medical-imaging', 'HealthImaging', 147371),
  new ServicePackage('mypy-boto3-arc-zonal-shift', 'ARCZonalShift', 147365),
  new ServicePackage('mypy-boto3-backup-gateway', 'BackupGateway', 147362),
  new ServicePackage('mypy-boto3-chime-sdk-media-pipelines', 'ChimeSDKMediaPipelines', 147359),
  new ServicePackage('mypy-boto3-s3outposts', 'S3Outposts', 147353),
  new ServicePackage('mypy-boto3-chime-sdk-identity', 'ChimeSDKIdentity', 147343),
  new ServicePackage('mypy-boto3-iotfleetwise', 'IoTFleetWise', 147328),
  new ServicePackage('mypy-boto3-omics', 'Omics', 147292),
  new ServicePackage('mypy-boto3-oam', 'CloudWatchObservabilityAccessManager', 147270),
  new ServicePackage('mypy-boto3-backupstorage', 'BackupStorage', 147260),
  new ServicePackage('mypy-boto3-simspaceweaver', 'SimSpaceWeaver', 147249),
  new ServicePackage('mypy-boto3-finspace-data', 'FinSpaceData', 147243),
  new ServicePackage('mypy-boto3-pipes', 'EventBridgePipes', 147223),
  new ServicePackage('mypy-boto3-voice-id', 'VoiceID', 147221),
  new ServicePackage('mypy-boto3-internetmonitor', 'CloudWatchInternetMonitor', 147208),
  new ServicePackage('mypy-boto3-amplifyuibuilder', 'AmplifyUIBuilder', 147184),
  new ServicePackage('mypy-boto3-ssm-contacts', 'SSMContacts', 147165),
  new ServicePackage('mypy-boto3-mediapackagev2', 'Mediapackagev2', 147160),
  new ServicePackage('mypy-boto3-support-app', 'SupportApp', 147093),
  new ServicePackage('mypy-boto3-m2', 'MainframeModernization', 147068),
  new ServicePackage('mypy-boto3-lookoutmetrics', 'LookoutMetrics', 147066),
  new ServicePackage('mypy-boto3-panorama', 'Panorama', 147006),
  new ServicePackage('mypy-boto3-sagemaker-metrics', 'SageMakerMetrics', 146914),
  new ServicePackage('mypy-boto3-billingconductor', 'BillingConductor', 146868),
  new ServicePackage('mypy-boto3-cloudtrail-data', 'CloudTrailDataService', 146855),
  new ServicePackage('mypy-boto3-osis', 'OpenSearchIngestion', 146820),
  new ServicePackage('mypy-boto3-drs', 'Drs', 146780),
  new ServicePackage('mypy-boto3-kendra-ranking', 'KendraRanking', 146770),
  new ServicePackage('mypy-boto3-nimble', 'NimbleStudio', 146749),
  new ServicePackage('mypy-boto3-datazone', 'DataZone', 146746),
  new ServicePackage('mypy-boto3-payment-cryptography', 'PaymentCryptographyControlPlane', 146701),
  new ServicePackage('mypy-boto3-launch-wizard', 'LaunchWizard', 146683),
  new ServicePackage(
    'mypy-boto3-kinesis-video-webrtc-storage',
    'KinesisVideoWebRTCStorage',
    146580
  ),
  new ServicePackage('mypy-boto3-eks-auth', 'EKSAuth', 146551),
  new ServicePackage('mypy-boto3-qbusiness', 'QBusiness', 146540),
  new ServicePackage('mypy-boto3-entityresolution', 'EntityResolution', 146479),
  new ServicePackage('mypy-boto3-connectcampaigns', 'ConnectCampaignService', 146462),
  new ServicePackage('mypy-boto3-rbin', 'RecycleBin', 146452),
  new ServicePackage('mypy-boto3-ivs-realtime', 'Ivsrealtime', 146419),
  new ServicePackage('mypy-boto3-bcm-data-exports', 'BillingandCostManagementDataExports', 146415),
  new ServicePackage('mypy-boto3-networkmonitor', 'CloudWatchNetworkMonitor', 146378),
  new ServicePackage('mypy-boto3-neptune-graph', 'NeptuneGraph', 146323),
  new ServicePackage('mypy-boto3-securitylake', 'SecurityLake', 146321),
  new ServicePackage('mypy-boto3-chime-sdk-voice', 'ChimeSDKVoice', 146270),
  new ServicePackage('mypy-boto3-route53-recovery-cluster', 'Route53RecoveryCluster', 146246),
  new ServicePackage('mypy-boto3-sagemaker-geospatial', 'SageMakergeospatialcapabilities', 146180),
  new ServicePackage('mypy-boto3-appfabric', 'AppFabric', 146159),
  new ServicePackage('mypy-boto3-cost-optimization-hub', 'CostOptimizationHub', 146156),
  new ServicePackage('mypy-boto3-tnb', 'TelcoNetworkBuilder', 146149),
  new ServicePackage('mypy-boto3-qconnect', 'QConnect', 146145),
  new ServicePackage('mypy-boto3-pinpoint-sms-voice-v2', 'PinpointSMSVoiceV2', 146126),
  new ServicePackage('mypy-boto3-vpc-lattice', 'VPCLattice', 146109),
  new ServicePackage('mypy-boto3-marketplace-agreement', 'AgreementService', 146093),
  new ServicePackage('mypy-boto3-iottwinmaker', 'IoTTwinMaker', 146071),
  new ServicePackage('mypy-boto3-marketplace-deployment', 'MarketplaceDeploymentService', 146046),
  new ServicePackage('mypy-boto3-trustedadvisor', 'TrustedAdvisorPublicAPI', 146045),
  new ServicePackage('mypy-boto3-connectcases', 'ConnectCases', 146033),
  new ServicePackage('mypy-boto3-resiliencehub', 'ResilienceHub', 146030),
  new ServicePackage('mypy-boto3-evidently', 'CloudWatchEvidently', 146010),
  new ServicePackage('mypy-boto3-controltower', 'ControlTower', 146008),
  new ServicePackage(
    'mypy-boto3-migration-hub-refactor-spaces',
    'MigrationHubRefactorSpaces',
    145981
  ),
  new ServicePackage('mypy-boto3-supplychain', 'SupplyChain', 145949),
  new ServicePackage('mypy-boto3-route53-recovery-readiness', 'Route53RecoveryReadiness', 145903),
  new ServicePackage('mypy-boto3-memorydb', 'MemoryDB', 145899),
  new ServicePackage('mypy-boto3-migrationhuborchestrator', 'MigrationHubOrchestrator', 145844),
  new ServicePackage('mypy-boto3-rum', 'CloudWatchRUM', 145837),
  new ServicePackage('mypy-boto3-pca-connector-ad', 'PcaConnectorAd', 145827),
  new ServicePackage('mypy-boto3-codeguru-security', 'CodeGuruSecurity', 145826),
  new ServicePackage('mypy-boto3-freetier', 'FreeTier', 145719),
  new ServicePackage('mypy-boto3-managedblockchain-query', 'ManagedBlockchainQuery', 145716),
  new ServicePackage(
    'mypy-boto3-payment-cryptography-data',
    'PaymentCryptographyDataPlane',
    145645
  ),
  new ServicePackage('mypy-boto3-cloudfront-keyvaluestore', 'CloudFrontKeyValueStore', 145579),
  new ServicePackage('mypy-boto3-privatenetworks', 'Private5G', 145524),
  new ServicePackage('mypy-boto3-resource-explorer-2', 'ResourceExplorer', 145494),
  new ServicePackage(
    'mypy-boto3-license-manager-user-subscriptions',
    'LicenseManagerUserSubscriptions',
    145339
  ),
  new ServicePackage(
    'mypy-boto3-license-manager-linux-subscriptions',
    'LicenseManagerLinuxSubscriptions',
    145285
  ),
  new ServicePackage('mypy-boto3-artifact', 'Artifact', 145284),
  new ServicePackage('mypy-boto3-chatbot', 'Chatbot', 144977),
  new ServicePackage('mypy-boto3-repostspace', 'RePostPrivate', 144891),
  new ServicePackage('mypy-boto3-inspector-scan', 'Inspectorscan', 144852),
  new ServicePackage('mypy-boto3-timestream-influxdb', 'TimestreamInfluxDB', 144193),
  new ServicePackage('mypy-boto3-codeconnections', 'CodeConnections', 107580),
  new ServicePackage('mypy-boto3-deadline', 'DeadlineCloud', 107447),
  new ServicePackage('mypy-boto3-controlcatalog', 'ControlCatalog', 99604),
  new ServicePackage('mypy-boto3-route53profiles', 'Route53Profiles', 2132)
]
