import { ServicePackage } from './servicePackage'

export const servicePackages: ServicePackage[] = [
  new ServicePackage('mypy-boto3-rds', 'RDS', 6436916),
  new ServicePackage('mypy-boto3-appflow', 'Appflow', 5108967),
  new ServicePackage('mypy-boto3-redshift-data', 'RedshiftDataAPIService', 3185438),
  new ServicePackage('mypy-boto3-s3', 'S3', 2335206),
  new ServicePackage('mypy-boto3-dynamodb', 'DynamoDB', 1113841),
  new ServicePackage('mypy-boto3-glue', 'Glue', 1017773),
  new ServicePackage('mypy-boto3-sqs', 'SQS', 971253),
  new ServicePackage('mypy-boto3-ec2', 'EC2', 780777),
  new ServicePackage('mypy-boto3-lambda', 'Lambda', 776323),
  new ServicePackage('mypy-boto3-cloudformation', 'CloudFormation', 647062),
  new ServicePackage('mypy-boto3-athena', 'Athena', 494949),
  new ServicePackage('mypy-boto3-appconfig', 'AppConfig', 432993),
  new ServicePackage('mypy-boto3-elbv2', 'ElasticLoadBalancingv2', 339616),
  new ServicePackage('mypy-boto3-secretsmanager', 'SecretsManager', 333786),
  new ServicePackage('mypy-boto3-sts', 'STS', 274090),
  new ServicePackage('mypy-boto3-events', 'EventBridge', 215060),
  new ServicePackage('mypy-boto3-ssm', 'SSM', 206892),
  new ServicePackage('mypy-boto3-cloudwatch', 'CloudWatch', 163893),
  new ServicePackage('mypy-boto3-kms', 'KMS', 158567),
  new ServicePackage('mypy-boto3-sns', 'SNS', 153526),
  new ServicePackage('mypy-boto3-logs', 'CloudWatchLogs', 134238),
  new ServicePackage('mypy-boto3-iam', 'IAM', 121332),
  new ServicePackage('mypy-boto3-ecr', 'ECR', 108338),
  new ServicePackage('mypy-boto3-ecs', 'ECS', 98118),
  new ServicePackage('mypy-boto3-route53', 'Route53', 95445),
  new ServicePackage('mypy-boto3-stepfunctions', 'SFN', 83379),
  new ServicePackage('mypy-boto3-kinesis', 'Kinesis', 72633),
  new ServicePackage('mypy-boto3-organizations', 'Organizations', 66527),
  new ServicePackage('mypy-boto3-sagemaker', 'SageMaker', 63261),
  new ServicePackage('mypy-boto3-autoscaling', 'AutoScaling', 60410),
  new ServicePackage('mypy-boto3-ce', 'CostExplorer', 59125),
  new ServicePackage('mypy-boto3-budgets', 'Budgets', 54985),
  new ServicePackage('mypy-boto3-marketplace-entitlement', 'MarketplaceEntitlementService', 53898),
  new ServicePackage('mypy-boto3-batch', 'Batch', 53461),
  new ServicePackage('mypy-boto3-ses', 'SES', 50409),
  new ServicePackage('mypy-boto3-apigateway', 'APIGateway', 47703),
  new ServicePackage('mypy-boto3-cognito-idp', 'CognitoIdentityProvider', 39700),
  new ServicePackage('mypy-boto3-sagemaker-runtime', 'SageMakerRuntime', 39509),
  new ServicePackage('mypy-boto3-opensearch', 'OpenSearchService', 38646),
  new ServicePackage('mypy-boto3-efs', 'EFS', 32435),
  new ServicePackage('mypy-boto3-es', 'ElasticsearchService', 31989),
  new ServicePackage('mypy-boto3-cloudfront', 'CloudFront', 30460),
  new ServicePackage('mypy-boto3-identitystore', 'IdentityStore', 27330),
  new ServicePackage('mypy-boto3-eks', 'EKS', 27181),
  new ServicePackage('mypy-boto3-application-autoscaling', 'ApplicationAutoScaling', 26674),
  new ServicePackage('mypy-boto3-pinpoint', 'Pinpoint', 25202),
  new ServicePackage('mypy-boto3-codepipeline', 'CodePipeline', 23793),
  new ServicePackage('mypy-boto3-xray', 'XRay', 22634),
  new ServicePackage('mypy-boto3-firehose', 'Firehose', 21622),
  new ServicePackage('mypy-boto3-emr', 'EMR', 21033),
  new ServicePackage('mypy-boto3-schemas', 'Schemas', 19992),
  new ServicePackage('mypy-boto3-signer', 'signer', 19946),
  new ServicePackage('mypy-boto3-iot', 'IoT', 16977),
  new ServicePackage('mypy-boto3-cloudtrail', 'CloudTrail', 16505),
  new ServicePackage('mypy-boto3-redshift', 'Redshift', 15212),
  new ServicePackage('mypy-boto3-iot-data', 'IoTDataPlane', 15191),
  new ServicePackage('mypy-boto3-location', 'LocationService', 14997),
  new ServicePackage('mypy-boto3-codeartifact', 'CodeArtifact', 14727),
  new ServicePackage('mypy-boto3-support', 'Support', 14585),
  new ServicePackage('mypy-boto3-resourcegroupstaggingapi', 'ResourceGroupsTaggingAPI', 13902),
  new ServicePackage('mypy-boto3-quicksight', 'QuickSight', 13674),
  new ServicePackage('mypy-boto3-elasticache', 'ElastiCache', 13356),
  new ServicePackage('mypy-boto3-ec2-instance-connect', 'EC2InstanceConnect', 13166),
  new ServicePackage('mypy-boto3-ecr-public', 'ECRPublic', 13121),
  new ServicePackage('mypy-boto3-codedeploy', 'CodeDeploy', 13016),
  new ServicePackage('mypy-boto3-textract', 'Textract', 12612),
  new ServicePackage('mypy-boto3-acm', 'ACM', 11276),
  new ServicePackage('mypy-boto3-greengrassv2', 'GreengrassV2', 11032),
  new ServicePackage('mypy-boto3-dlm', 'DLM', 10654),
  new ServicePackage('mypy-boto3-config', 'ConfigService', 10561),
  new ServicePackage('mypy-boto3-serverlessrepo', 'ServerlessApplicationRepository', 10385),
  new ServicePackage('mypy-boto3-transcribe', 'TranscribeService', 10197),
  new ServicePackage('mypy-boto3-sesv2', 'SESV2', 9920),
  new ServicePackage('mypy-boto3-rekognition', 'Rekognition', 9857),
  new ServicePackage('mypy-boto3-rds-data', 'RDSDataService', 9652),
  new ServicePackage('mypy-boto3-lakeformation', 'LakeFormation', 9636),
  new ServicePackage('mypy-boto3-ebs', 'EBS', 9394),
  new ServicePackage('mypy-boto3-securityhub', 'SecurityHub', 8932),
  new ServicePackage('mypy-boto3-apigatewaymanagementapi', 'ApiGatewayManagementApi', 8889),
  new ServicePackage('mypy-boto3-wafv2', 'WAFV2', 8584),
  new ServicePackage('mypy-boto3-s3control', 'S3Control', 8393),
  new ServicePackage('mypy-boto3-medialive', 'MediaLive', 8289),
  new ServicePackage('mypy-boto3-kafka', 'Kafka', 8227),
  new ServicePackage('mypy-boto3-sdb', 'SimpleDB', 7836),
  new ServicePackage('mypy-boto3-directconnect', 'DirectConnect', 7798),
  new ServicePackage('mypy-boto3-acm-pca', 'ACMPCA', 7724),
  new ServicePackage('mypy-boto3-codebuild', 'CodeBuild', 7507),
  new ServicePackage('mypy-boto3-backup', 'Backup', 7445),
  new ServicePackage('mypy-boto3-transfer', 'Transfer', 7381),
  new ServicePackage('mypy-boto3-appsync', 'AppSync', 7315),
  new ServicePackage('mypy-boto3-dynamodbstreams', 'DynamoDBStreams', 7293),
  new ServicePackage('mypy-boto3-greengrass', 'Greengrass', 7178),
  new ServicePackage('mypy-boto3-appmesh', 'AppMesh', 7131),
  new ServicePackage('mypy-boto3-appstream', 'AppStream', 7091),
  new ServicePackage('mypy-boto3-shield', 'Shield', 7081),
  new ServicePackage('mypy-boto3-ram', 'RAM', 7077),
  new ServicePackage('mypy-boto3-service-quotas', 'ServiceQuotas', 6988),
  new ServicePackage('mypy-boto3-snowball', 'Snowball', 6976),
  new ServicePackage('mypy-boto3-elb', 'ElasticLoadBalancing', 6970),
  new ServicePackage('mypy-boto3-sso-admin', 'SSOAdmin', 6966),
  new ServicePackage('mypy-boto3-neptune', 'Neptune', 6937),
  new ServicePackage('mypy-boto3-servicecatalog', 'ServiceCatalog', 6855),
  new ServicePackage('mypy-boto3-accessanalyzer', 'AccessAnalyzer', 6844),
  new ServicePackage('mypy-boto3-docdb', 'DocDB', 6754),
  new ServicePackage('mypy-boto3-dax', 'DAX', 6728),
  new ServicePackage('mypy-boto3-sso-oidc', 'SSOOIDC', 6569),
  new ServicePackage('mypy-boto3-timestream-write', 'TimestreamWrite', 6503),
  new ServicePackage('mypy-boto3-elasticbeanstalk', 'ElasticBeanstalk', 6419),
  new ServicePackage('mypy-boto3-compute-optimizer', 'ComputeOptimizer', 6352),
  new ServicePackage('mypy-boto3-polly', 'Polly', 6338),
  new ServicePackage('mypy-boto3-mediatailor', 'MediaTailor', 6218),
  new ServicePackage('mypy-boto3-glacier', 'Glacier', 6200),
  new ServicePackage('mypy-boto3-workdocs', 'WorkDocs', 6156),
  new ServicePackage('mypy-boto3-groundstation', 'GroundStation', 6151),
  new ServicePackage('mypy-boto3-datasync', 'DataSync', 6135),
  new ServicePackage('mypy-boto3-workspaces', 'WorkSpaces', 6125),
  new ServicePackage('mypy-boto3-connectparticipant', 'ConnectParticipant', 6107),
  new ServicePackage('mypy-boto3-forecast', 'ForecastService', 6096),
  new ServicePackage('mypy-boto3-discovery', 'ApplicationDiscoveryService', 6073),
  new ServicePackage('mypy-boto3-clouddirectory', 'CloudDirectory', 6049),
  new ServicePackage('mypy-boto3-swf', 'SWF', 6040),
  new ServicePackage('mypy-boto3-frauddetector', 'FraudDetector', 6031),
  new ServicePackage('mypy-boto3-fsx', 'FSx', 5989),
  new ServicePackage('mypy-boto3-comprehend', 'Comprehend', 5971),
  new ServicePackage('mypy-boto3-meteringmarketplace', 'MarketplaceMetering', 5696),
  new ServicePackage('mypy-boto3-mwaa', 'MWAA', 5693),
  new ServicePackage('mypy-boto3-kinesisvideo', 'KinesisVideo', 5667),
  new ServicePackage('mypy-boto3-connect', 'Connect', 5563),
  new ServicePackage('mypy-boto3-emr-containers', 'EMRContainers', 5428),
  new ServicePackage('mypy-boto3-timestream-query', 'TimestreamQuery', 5411),
  new ServicePackage('mypy-boto3-apigatewayv2', 'ApiGatewayV2', 5402),
  new ServicePackage('mypy-boto3-cognito-identity', 'CognitoIdentity', 5373),
  new ServicePackage('mypy-boto3-ivs', 'IVS', 5282),
  new ServicePackage('mypy-boto3-inspector', 'Inspector', 5267),
  new ServicePackage('mypy-boto3-translate', 'Translate', 5245),
  new ServicePackage('mypy-boto3-amplify', 'Amplify', 5055),
  new ServicePackage(
    'mypy-boto3-sagemaker-featurestore-runtime',
    'SageMakerFeatureStoreRuntime',
    5019
  ),
  new ServicePackage('mypy-boto3-keyspaces', 'Keyspaces', 5012),
  new ServicePackage('mypy-boto3-kinesis-video-archived-media', 'KinesisVideoArchivedMedia', 4993),
  new ServicePackage('mypy-boto3-pricing', 'Pricing', 4945),
  new ServicePackage('mypy-boto3-databrew', 'GlueDataBrew', 4904),
  new ServicePackage('mypy-boto3-kinesis-video-media', 'KinesisVideoMedia', 4896),
  new ServicePackage('mypy-boto3-devops-guru', 'DevOpsGuru', 4894),
  new ServicePackage('mypy-boto3-customer-profiles', 'CustomerProfiles', 4858),
  new ServicePackage('mypy-boto3-kendra', 'kendra', 4761),
  new ServicePackage('mypy-boto3-mediaconvert', 'MediaConvert', 4742),
  new ServicePackage('mypy-boto3-pinpoint-email', 'PinpointEmail', 4735),
  new ServicePackage('mypy-boto3-lexv2-models', 'LexModelsV2', 4658),
  new ServicePackage('mypy-boto3-chime', 'Chime', 4616),
  new ServicePackage('mypy-boto3-lexv2-runtime', 'LexRuntimeV2', 4610),
  new ServicePackage('mypy-boto3-route53resolver', 'Route53Resolver', 4573),
  new ServicePackage('mypy-boto3-mediastore', 'MediaStore', 4505),
  new ServicePackage('mypy-boto3-dms', 'DatabaseMigrationService', 4503),
  new ServicePackage('mypy-boto3-guardduty', 'GuardDuty', 4461),
  new ServicePackage('mypy-boto3-cloudsearchdomain', 'CloudSearchDomain', 4452),
  new ServicePackage('mypy-boto3-devicefarm', 'DeviceFarm', 4446),
  new ServicePackage('mypy-boto3-codecommit', 'CodeCommit', 4387),
  new ServicePackage('mypy-boto3-waf', 'WAF', 4298),
  new ServicePackage('mypy-boto3-outposts', 'Outposts', 4284),
  new ServicePackage('mypy-boto3-mturk', 'MTurk', 4266),
  new ServicePackage('mypy-boto3-sso', 'SSO', 4266),
  new ServicePackage('mypy-boto3-cloudsearch', 'CloudSearch', 4256),
  new ServicePackage('mypy-boto3-cur', 'CostandUsageReportService', 4208),
  new ServicePackage('mypy-boto3-savingsplans', 'SavingsPlans', 4185),
  new ServicePackage('mypy-boto3-elastictranscoder', 'ElasticTranscoder', 4167),
  new ServicePackage('mypy-boto3-imagebuilder', 'imagebuilder', 4165),
  new ServicePackage('mypy-boto3-route53domains', 'Route53Domains', 4130),
  new ServicePackage('mypy-boto3-globalaccelerator', 'GlobalAccelerator', 4128),
  new ServicePackage('mypy-boto3-marketplace-catalog', 'MarketplaceCatalog', 4111),
  new ServicePackage('mypy-boto3-mediapackage', 'MediaPackage', 4101),
  new ServicePackage('mypy-boto3-iotwireless', 'IoTWireless', 4098),
  new ServicePackage('mypy-boto3-network-firewall', 'NetworkFirewall', 4080),
  new ServicePackage('mypy-boto3-mediaconnect', 'MediaConnect', 4076),
  new ServicePackage('mypy-boto3-lightsail', 'Lightsail', 4074),
  new ServicePackage('mypy-boto3-fis', 'FIS', 4039),
  new ServicePackage('mypy-boto3-resource-groups', 'ResourceGroups', 4019),
  new ServicePackage('mypy-boto3-cloud9', 'Cloud9', 4003),
  new ServicePackage('mypy-boto3-ds', 'DirectoryService', 3994),
  new ServicePackage('mypy-boto3-sms', 'SMS', 3986),
  new ServicePackage('mypy-boto3-datapipeline', 'DataPipeline', 3981),
  new ServicePackage('mypy-boto3-sagemaker-a2i-runtime', 'AugmentedAIRuntime', 3981),
  new ServicePackage('mypy-boto3-servicediscovery', 'ServiceDiscovery', 3973),
  new ServicePackage('mypy-boto3-iot-jobs-data', 'IoTJobsDataPlane', 3964),
  new ServicePackage('mypy-boto3-comprehendmedical', 'ComprehendMedical', 3962),
  new ServicePackage('mypy-boto3-fms', 'FMS', 3957),
  new ServicePackage('mypy-boto3-waf-regional', 'WAFRegional', 3955),
  new ServicePackage('mypy-boto3-gamelift', 'GameLift', 3948),
  new ServicePackage('mypy-boto3-pi', 'PI', 3947),
  new ServicePackage('mypy-boto3-personalize', 'Personalize', 3944),
  new ServicePackage('mypy-boto3-mediapackage-vod', 'MediaPackageVod', 3939),
  new ServicePackage('mypy-boto3-networkmanager', 'NetworkManager', 3938),
  new ServicePackage('mypy-boto3-iotevents-data', 'IoTEventsData', 3937),
  new ServicePackage('mypy-boto3-lex-runtime', 'LexRuntimeService', 3936),
  new ServicePackage('mypy-boto3-forecastquery', 'ForecastQueryService', 3934),
  new ServicePackage('mypy-boto3-application-insights', 'ApplicationInsights', 3932),
  new ServicePackage('mypy-boto3-alexaforbusiness', 'AlexaForBusiness', 3929),
  new ServicePackage('mypy-boto3-macie', 'Macie', 3929),
  new ServicePackage('mypy-boto3-cognito-sync', 'CognitoSync', 3928),
  new ServicePackage('mypy-boto3-robomaker', 'RoboMaker', 3928),
  new ServicePackage('mypy-boto3-personalize-runtime', 'PersonalizeRuntime', 3927),
  new ServicePackage('mypy-boto3-pinpoint-sms-voice', 'PinpointSMSVoice', 3927),
  new ServicePackage('mypy-boto3-codeguru-reviewer', 'CodeGuruReviewer', 3926),
  new ServicePackage('mypy-boto3-codestar', 'CodeStar', 3926),
  new ServicePackage('mypy-boto3-codestar-notifications', 'CodeStarNotifications', 3926),
  new ServicePackage('mypy-boto3-kinesisanalytics', 'KinesisAnalytics', 3926),
  new ServicePackage('mypy-boto3-lex-models', 'LexModelBuildingService', 3926),
  new ServicePackage('mypy-boto3-managedblockchain', 'ManagedBlockchain', 3926),
  new ServicePackage('mypy-boto3-dataexchange', 'DataExchange', 3924),
  new ServicePackage('mypy-boto3-health', 'Health', 3923),
  new ServicePackage('mypy-boto3-importexport', 'ImportExport', 3923),
  new ServicePackage('mypy-boto3-autoscaling-plans', 'AutoScalingPlans', 3922),
  new ServicePackage('mypy-boto3-cloudhsmv2', 'CloudHSMV2', 3922),
  new ServicePackage('mypy-boto3-opsworks', 'OpsWorks', 3922),
  new ServicePackage('mypy-boto3-iotthingsgraph', 'IoTThingsGraph', 3921),
  new ServicePackage('mypy-boto3-machinelearning', 'MachineLearning', 3921),
  new ServicePackage('mypy-boto3-detective', 'Detective', 3920),
  new ServicePackage('mypy-boto3-kinesisanalyticsv2', 'KinesisAnalyticsV2', 3920),
  new ServicePackage('mypy-boto3-license-manager', 'LicenseManager', 3920),
  new ServicePackage('mypy-boto3-personalize-events', 'PersonalizeEvents', 3920),
  new ServicePackage('mypy-boto3-storagegateway', 'StorageGateway', 3920),
  new ServicePackage('mypy-boto3-mediastore-data', 'MediaStoreData', 3918),
  new ServicePackage('mypy-boto3-workmail', 'WorkMail', 3917),
  new ServicePackage('mypy-boto3-iotanalytics', 'IoTAnalytics', 3916),
  new ServicePackage('mypy-boto3-iotevents', 'IoTEvents', 3916),
  new ServicePackage('mypy-boto3-mgh', 'MigrationHub', 3916),
  new ServicePackage('mypy-boto3-qldb', 'QLDB', 3916),
  new ServicePackage('mypy-boto3-iot1click-projects', 'IoT1ClickProjects', 3915),
  new ServicePackage('mypy-boto3-cloudhsm', 'CloudHSM', 3914),
  new ServicePackage(
    'mypy-boto3-marketplacecommerceanalytics',
    'MarketplaceCommerceAnalytics',
    3913
  ),
  new ServicePackage('mypy-boto3-opsworkscm', 'OpsWorksCM', 3913),
  new ServicePackage('mypy-boto3-qldb-session', 'QLDBSession', 3913),
  new ServicePackage('mypy-boto3-mobile', 'Mobile', 3912),
  new ServicePackage('mypy-boto3-worklink', 'WorkLink', 3911),
  new ServicePackage('mypy-boto3-iot1click-devices', 'IoT1ClickDevicesService', 3910),
  new ServicePackage('mypy-boto3-mq', 'MQ', 3910),
  new ServicePackage('mypy-boto3-sms-voice', 'PinpointSMSVoice', 3910),
  new ServicePackage('mypy-boto3-codeguruprofiler', 'CodeGuruProfiler', 3909),
  new ServicePackage('mypy-boto3-elastic-inference', 'ElasticInference', 3909),
  new ServicePackage('mypy-boto3-workmailmessageflow', 'WorkMailMessageFlow', 3904),
  new ServicePackage('mypy-boto3-kinesis-video-signaling', 'KinesisVideoSignalingChannels', 3903),
  new ServicePackage('mypy-boto3-codestar-connections', 'CodeStarconnections', 3900),
  new ServicePackage('mypy-boto3-iotsecuretunneling', 'IoTSecureTunneling', 3898),
  new ServicePackage('mypy-boto3-migrationhub-config', 'MigrationHubConfig', 3898),
  new ServicePackage('mypy-boto3-synthetics', 'Synthetics', 3813),
  new ServicePackage('mypy-boto3-macie2', 'Macie2', 3812),
  new ServicePackage('mypy-boto3-iotsitewise', 'IoTSiteWise', 3805),
  new ServicePackage('mypy-boto3-auditmanager', 'AuditManager', 3747),
  new ServicePackage('mypy-boto3-braket', 'Braket', 3693),
  new ServicePackage('mypy-boto3-honeycode', 'Honeycode', 3684),
  new ServicePackage('mypy-boto3-proton', 'Proton', 3677),
  new ServicePackage('mypy-boto3-amplifybackend', 'AmplifyBackend', 3669),
  new ServicePackage('mypy-boto3-s3outposts', 'S3Outposts', 3649),
  new ServicePackage('mypy-boto3-lookoutvision', 'LookoutforVision', 3624),
  new ServicePackage('mypy-boto3-iotdeviceadvisor', 'IoTDeviceAdvisor', 3618),
  new ServicePackage('mypy-boto3-servicecatalog-appregistry', 'AppRegistry', 3613),
  new ServicePackage('mypy-boto3-amp', 'PrometheusService', 3607),
  new ServicePackage('mypy-boto3-sagemaker-edge', 'SagemakerEdgeManager', 3604),
  new ServicePackage('mypy-boto3-appintegrations', 'AppIntegrationsService', 3602),
  new ServicePackage('mypy-boto3-connect-contact-lens', 'ConnectContactLens', 3600),
  new ServicePackage('mypy-boto3-healthlake', 'HealthLake', 3597),
  new ServicePackage('mypy-boto3-wellarchitected', 'WellArchitected', 3593),
  new ServicePackage('mypy-boto3-iotfleethub', 'IoTFleetHub', 3587),
  new ServicePackage('mypy-boto3-grafana', 'ManagedGrafana', 3507),
  new ServicePackage('mypy-boto3-account', 'Account', 3207),
  new ServicePackage('mypy-boto3-ssm-incidents', 'SSMIncidents', 3204),
  new ServicePackage('mypy-boto3-lookoutequipment', 'LookoutEquipment', 3195),
  new ServicePackage('mypy-boto3-appconfigdata', 'AppConfigData', 3194),
  new ServicePackage('mypy-boto3-lookoutmetrics', 'LookoutMetrics', 3183),
  new ServicePackage('mypy-boto3-mgn', 'mgn', 3175),
  new ServicePackage('mypy-boto3-apprunner', 'AppRunner', 3160),
  new ServicePackage('mypy-boto3-nimble', 'NimbleStudio', 3156),
  new ServicePackage('mypy-boto3-finspace-data', 'FinSpaceData', 3129),
  new ServicePackage('mypy-boto3-finspace', 'finspace', 3098),
  new ServicePackage('mypy-boto3-ssm-contacts', 'SSMContacts', 3098),
  new ServicePackage('mypy-boto3-applicationcostprofiler', 'ApplicationCostProfiler', 3031),
  new ServicePackage('mypy-boto3-chime-sdk-meetings', 'ChimeSDKMeetings', 2972),
  new ServicePackage(
    'mypy-boto3-route53-recovery-control-config',
    'Route53RecoveryControlConfig',
    2907
  ),
  new ServicePackage('mypy-boto3-route53-recovery-cluster', 'Route53RecoveryCluster', 2887),
  new ServicePackage('mypy-boto3-route53-recovery-readiness', 'Route53RecoveryReadiness', 2878),
  new ServicePackage('mypy-boto3-memorydb', 'MemoryDB', 2854),
  new ServicePackage('mypy-boto3-chime-sdk-messaging', 'ChimeSDKMessaging', 2844),
  new ServicePackage('mypy-boto3-panorama', 'Panorama', 2839),
  new ServicePackage('mypy-boto3-snow-device-management', 'SnowDeviceManagement', 2782),
  new ServicePackage('mypy-boto3-chime-sdk-identity', 'ChimeSDKIdentity', 2777),
  new ServicePackage(
    'mypy-boto3-migration-hub-refactor-spaces',
    'MigrationHubRefactorSpaces',
    2666
  ),
  new ServicePackage('mypy-boto3-evidently', 'CloudWatchEvidently', 2659),
  new ServicePackage('mypy-boto3-wisdom', 'ConnectWisdomService', 2624),
  new ServicePackage('mypy-boto3-kafkaconnect', 'KafkaConnect', 2611),
  new ServicePackage('mypy-boto3-cloudcontrol', 'CloudControlApi', 2600),
  new ServicePackage('mypy-boto3-voice-id', 'VoiceID', 2593),
  new ServicePackage('mypy-boto3-inspector2', 'Inspector2', 2560),
  new ServicePackage('mypy-boto3-workspaces-web', 'WorkSpacesWeb', 2482),
  new ServicePackage('mypy-boto3-iottwinmaker', 'IoTTwinMaker', 2477),
  new ServicePackage('mypy-boto3-amplifyuibuilder', 'AmplifyUIBuilder', 2472),
  new ServicePackage('mypy-boto3-emr-serverless', 'EMRServerless', 2472),
  new ServicePackage('mypy-boto3-backup-gateway', 'BackupGateway', 2471),
  new ServicePackage('mypy-boto3-drs', 'drs', 2467),
  new ServicePackage('mypy-boto3-rbin', 'RecycleBin', 2458),
  new ServicePackage(
    'mypy-boto3-migrationhubstrategy',
    'MigrationHubStrategyRecommendations',
    2457
  ),
  new ServicePackage('mypy-boto3-rum', 'CloudWatchRUM', 2456),
  new ServicePackage('mypy-boto3-resiliencehub', 'ResilienceHub', 2451),
  new ServicePackage('mypy-boto3-billingconductor', 'BillingConductor', 2438),
  new ServicePackage('mypy-boto3-gamesparks', 'GameSparks', 2380),
  new ServicePackage('mypy-boto3-pinpoint-sms-voice-v2', 'PinpointSMSVoiceV2', 2367),
  new ServicePackage('mypy-boto3-ivschat', 'ivschat', 2346),
  new ServicePackage('mypy-boto3-chime-sdk-media-pipelines', 'ChimeSDKMediaPipelines', 2324),
  new ServicePackage('mypy-boto3-scheduler', 'EventBridgeScheduler', 2275),
  new ServicePackage('mypy-boto3-opensearchserverless', 'OpenSearchServiceServerless', 2124),
  new ServicePackage('mypy-boto3-redshift-serverless', 'RedshiftServerless', 2033),
  new ServicePackage('mypy-boto3-m2', 'MainframeModernization', 1948),
  new ServicePackage('mypy-boto3-iotfleetwise', 'IoTFleetWise', 1939),
  new ServicePackage('mypy-boto3-privatenetworks', 'Private5G', 1846),
  new ServicePackage('mypy-boto3-chime-sdk-voice', 'ChimeSDKVoice', 1806),
  new ServicePackage('mypy-boto3-backupstorage', 'BackupStorage', 1781),
  new ServicePackage('mypy-boto3-iot-roborunner', 'IoTRoboRunner', 1781),
  new ServicePackage('mypy-boto3-connectcases', 'ConnectCases', 1780),
  new ServicePackage('mypy-boto3-support-app', 'SupportApp', 1780),
  new ServicePackage('mypy-boto3-controltower', 'ControlTower', 1779),
  new ServicePackage('mypy-boto3-connectcampaigns', 'ConnectCampaignService', 1778),
  new ServicePackage('mypy-boto3-migrationhuborchestrator', 'MigrationHubOrchestrator', 1772),
  new ServicePackage(
    'mypy-boto3-license-manager-user-subscriptions',
    'LicenseManagerUserSubscriptions',
    1770
  ),
  new ServicePackage('mypy-boto3-rolesanywhere', 'IAMRolesAnywhere', 1762),
  new ServicePackage('mypy-boto3-ssm-sap', 'SsmSap', 1744),
  new ServicePackage('mypy-boto3-resource-explorer-2', 'ResourceExplorer', 1708),
  new ServicePackage('mypy-boto3-omics', 'Omics', 1699),
  new ServicePackage('mypy-boto3-securitylake', 'SecurityLake', 1683),
  new ServicePackage('mypy-boto3-arc-zonal-shift', 'ARCZonalShift', 1681),
  new ServicePackage('mypy-boto3-cleanrooms', 'CleanRoomsService', 1679),
  new ServicePackage('mypy-boto3-codecatalyst', 'CodeCatalyst', 1674),
  new ServicePackage('mypy-boto3-kendra-ranking', 'KendraRanking', 1674),
  new ServicePackage('mypy-boto3-oam', 'CloudWatchObservabilityAccessManager', 1672),
  new ServicePackage('mypy-boto3-docdb-elastic', 'DocDBElastic', 1671),
  new ServicePackage('mypy-boto3-sagemaker-geospatial', 'SageMakergeospatialcapabilities', 1667),
  new ServicePackage('mypy-boto3-pipes', 'EventBridgePipes', 1666),
  new ServicePackage('mypy-boto3-simspaceweaver', 'SimSpaceWeaver', 1666),
  new ServicePackage('mypy-boto3-kinesis-video-webrtc-storage', 'KinesisVideoWebRTCStorage', 1645),
  new ServicePackage('mypy-boto3-sagemaker-metrics', 'SageMakerMetrics', 1637),
  new ServicePackage(
    'mypy-boto3-license-manager-linux-subscriptions',
    'LicenseManagerLinuxSubscriptions',
    1631
  ),
  new ServicePackage('mypy-boto3-cloudtrail-data', 'CloudTrailDataService', 397)
]
