import { PypiPackage } from "./pypi";


export class ServicePackage implements PypiPackage {
    serviceName: string;
    moduleName: string;
    version: string;
    installed: boolean;
    recommended: boolean;
    downloads: number;

    constructor(moduleName: string, serviceName: string, downloads: number = 0) {
        this.serviceName = serviceName;
        this.moduleName = moduleName;
        this.version = '';
        this.installed = false;
        this.recommended = false;
        this.downloads = downloads;
    }

    getDetail(): string {
        return `boto3.client('${this.getExtraName()}') auto-complete and type annotations`;
    }
    getDescription(): string {
        if (this.installed) { return '(installed)'; }
        if (this.recommended) { return '(recommended)'; }
        return '';
    }
    getShortLabel(): string {
        return this.serviceName;
    }
    getLabel(): string {
        return `${this.serviceName} ${this.version}`;
    }
    getExtraName(): string {
        return this.moduleName.replace('mypy-boto3-', '');
    }
    getDocsURL(): string {
        const linkName = this.moduleName.replace(/-/g, '_');
        return `https://vemel.github.io/boto3_stubs_docs/${linkName}/`;
    }
}

export const servicePackages: ServicePackage[] = [
    new ServicePackage('mypy-boto3-mediaconvert', 'MediaConvert', 4144),
    new ServicePackage('mypy-boto3-translate', 'Translate', 4759),
    new ServicePackage('mypy-boto3-amp', 'PrometheusService', 3064),
    new ServicePackage('mypy-boto3-signer', 'signer', 3889),
    new ServicePackage('mypy-boto3-swf', 'SWF', 3927),
    new ServicePackage('mypy-boto3-codepipeline', 'CodePipeline', 4222),
    new ServicePackage('mypy-boto3-pi', 'PI', 3895),
    new ServicePackage('mypy-boto3-dlm', 'DLM', 3848),
    new ServicePackage('mypy-boto3-securityhub', 'SecurityHub', 5192),
    new ServicePackage('mypy-boto3-identitystore', 'IdentityStore', 3330),
    new ServicePackage('mypy-boto3-kms', 'KMS', 26174),
    new ServicePackage('mypy-boto3-cloudwatch', 'CloudWatch', 48296),
    new ServicePackage('mypy-boto3-dms', 'DatabaseMigrationService', 4570),
    new ServicePackage('mypy-boto3-mturk', 'MTurk', 4337),
    new ServicePackage('mypy-boto3-servicediscovery', 'ServiceDiscovery', 3935),
    new ServicePackage('mypy-boto3-databrew', 'GlueDataBrew', 3122),
    new ServicePackage('mypy-boto3-appmesh', 'AppMesh', 4061),
    new ServicePackage('mypy-boto3-sqs', 'SQS', 170665),
    new ServicePackage('mypy-boto3-iotdeviceadvisor', 'IoTDeviceAdvisor', 3108),
    new ServicePackage('mypy-boto3-cloudtrail', 'CloudTrail', 14309),
    new ServicePackage('mypy-boto3-emr', 'EMR', 5861),
    new ServicePackage('mypy-boto3-kafka', 'Kafka', 4053),
    new ServicePackage('mypy-boto3-autoscaling', 'AutoScaling', 10610),
    new ServicePackage('mypy-boto3-cloudcontrol', 'CloudControlApi', 1486),
    new ServicePackage('mypy-boto3-accessanalyzer', 'AccessAnalyzer', 5510),
    new ServicePackage('mypy-boto3-opsworks', 'OpsWorks', 3900),
    new ServicePackage('mypy-boto3-detective', 'Detective', 3821),
    new ServicePackage('mypy-boto3-opensearch', 'OpenSearchService', 1893),
    new ServicePackage('mypy-boto3-ebs', 'EBS', 3979),
    new ServicePackage('mypy-boto3-ses', 'SES', 16849),
    new ServicePackage('mypy-boto3-chime', 'Chime', 4517),
    new ServicePackage('mypy-boto3-lightsail', 'Lightsail', 3865),
    new ServicePackage('mypy-boto3-elbv2', 'ElasticLoadBalancingv2', 9692),
    new ServicePackage('mypy-boto3-healthlake', 'HealthLake', 3063),
    new ServicePackage('mypy-boto3-amplifybackend', 'AmplifyBackend', 3140),
    new ServicePackage('mypy-boto3-memorydb', 'MemoryDB', 1738),
    new ServicePackage('mypy-boto3-schemas', 'Schemas', 3824),
    new ServicePackage('mypy-boto3-codecommit', 'CodeCommit', 3952),
    new ServicePackage('mypy-boto3-sms', 'SMS', 3866),
    new ServicePackage('mypy-boto3-kinesis', 'Kinesis', 8282),
    new ServicePackage('mypy-boto3-apigateway', 'APIGateway', 7094),
    new ServicePackage('mypy-boto3-codeguruprofiler', 'CodeGuruProfiler', 3816),
    new ServicePackage('mypy-boto3-codebuild', 'CodeBuild', 4360),
    new ServicePackage('mypy-boto3-networkmanager', 'NetworkManager', 3817),
    new ServicePackage('mypy-boto3-iam', 'IAM', 34023),
    new ServicePackage('mypy-boto3-iotsecuretunneling', 'IoTSecureTunneling', 3860),
    new ServicePackage('mypy-boto3-frauddetector', 'FraudDetector', 3859),
    new ServicePackage('mypy-boto3-es', 'ElasticsearchService', 6800),
    new ServicePackage('mypy-boto3-importexport', 'ImportExport', 3935),
    new ServicePackage('mypy-boto3-forecastquery', 'ForecastQueryService', 3846),
    new ServicePackage('mypy-boto3-rekognition', 'Rekognition', 4050),
    new ServicePackage('mypy-boto3-fis', 'FIS', 2524),
    new ServicePackage('mypy-boto3-kafkaconnect', 'KafkaConnect', 1524),
    new ServicePackage('mypy-boto3-applicationcostprofiler', 'ApplicationCostProfiler', 2431),
    new ServicePackage('mypy-boto3-waf', 'WAF', 3879),
    new ServicePackage('mypy-boto3-mgn', 'mgn', 2527),
    new ServicePackage('mypy-boto3-route53', 'Route53', 16622),
    new ServicePackage('mypy-boto3-sagemaker', 'SageMaker', 9888),
    new ServicePackage('mypy-boto3-medialive', 'MediaLive', 4612),
    new ServicePackage('mypy-boto3-workmailmessageflow', 'WorkMailMessageFlow', 3897),
    new ServicePackage('mypy-boto3-iotfleethub', 'IoTFleetHub', 3064),
    new ServicePackage('mypy-boto3-apigatewaymanagementapi', 'ApiGatewayManagementApi', 4427),
    new ServicePackage('mypy-boto3-polly', 'Polly', 3959),
    new ServicePackage('mypy-boto3-ivs', 'IVS', 3310),
    new ServicePackage('mypy-boto3-lambda', 'Lambda', 101033),
    new ServicePackage('mypy-boto3-datapipeline', 'DataPipeline', 5769),
    new ServicePackage('mypy-boto3-cloudsearchdomain', 'CloudSearchDomain', 3900),
    new ServicePackage('mypy-boto3-events', 'EventBridge', 10305),
    new ServicePackage('mypy-boto3-kinesisanalytics', 'KinesisAnalytics', 3823),
    new ServicePackage('mypy-boto3-codeartifact', 'CodeArtifact', 3692),
    new ServicePackage('mypy-boto3-cloudsearch', 'CloudSearch', 3932),
    new ServicePackage('mypy-boto3-resourcegroupstaggingapi', 'ResourceGroupsTaggingAPI', 5084),
    new ServicePackage('mypy-boto3-lookoutvision', 'LookoutforVision', 3109),
    new ServicePackage('mypy-boto3-honeycode', 'Honeycode', 3957),
    new ServicePackage('mypy-boto3-comprehendmedical', 'ComprehendMedical', 3841),
    new ServicePackage('mypy-boto3-iotanalytics', 'IoTAnalytics', 3893),
    new ServicePackage('mypy-boto3-guardduty', 'GuardDuty', 3882),
    new ServicePackage('mypy-boto3-transcribe', 'TranscribeService', 4494),
    new ServicePackage('mypy-boto3-config', 'ConfigService', 4407),
    new ServicePackage('mypy-boto3-discovery', 'ApplicationDiscoveryService', 3846),
    new ServicePackage('mypy-boto3-connect', 'Connect', 3974),
    new ServicePackage('mypy-boto3-lookoutmetrics', 'LookoutMetrics', 2584),
    new ServicePackage('mypy-boto3-quicksight', 'QuickSight', 4972),
    new ServicePackage('mypy-boto3-textract', 'Textract', 4598),
    new ServicePackage('mypy-boto3-greengrassv2', 'GreengrassV2', 4192),
    new ServicePackage('mypy-boto3-sso', 'SSO', 3902),
    new ServicePackage('mypy-boto3-pinpoint', 'Pinpoint', 8674),
    new ServicePackage('mypy-boto3-account', 'Account', 1472),
    new ServicePackage('mypy-boto3-appstream', 'AppStream', 3875),
    new ServicePackage('mypy-boto3-dynamodbstreams', 'DynamoDBStreams', 4882),
    new ServicePackage('mypy-boto3-mobile', 'Mobile', 3857),
    new ServicePackage('mypy-boto3-dynamodb', 'DynamoDB', 598582),
    new ServicePackage('mypy-boto3-health', 'Health', 3890),
    new ServicePackage('mypy-boto3-machinelearning', 'MachineLearning', 3954),
    new ServicePackage('mypy-boto3-outposts', 'Outposts', 3792),
    new ServicePackage('mypy-boto3-grafana', 'ManagedGrafana', 1369),
    new ServicePackage('mypy-boto3-ssm', 'SSM', 72528),
    new ServicePackage('mypy-boto3-sts', 'STS', 58117),
    new ServicePackage('mypy-boto3-worklink', 'WorkLink', 3932),
    new ServicePackage('mypy-boto3-fsx', 'FSx', 3881),
    new ServicePackage('mypy-boto3-directconnect', 'DirectConnect', 4084),
    new ServicePackage('mypy-boto3-gamelift', 'GameLift', 3915),
    new ServicePackage('mypy-boto3-kinesisvideo', 'KinesisVideo', 3823),
    new ServicePackage('mypy-boto3-docdb', 'DocDB', 3840),
    new ServicePackage('mypy-boto3-ram', 'RAM', 4163),
    new ServicePackage('mypy-boto3-dax', 'DAX', 3907),
    new ServicePackage('mypy-boto3-workspaces', 'WorkSpaces', 3944),
    new ServicePackage('mypy-boto3-mediaconnect', 'MediaConnect', 4226),
    new ServicePackage('mypy-boto3-managedblockchain', 'ManagedBlockchain', 3896),
    new ServicePackage('mypy-boto3-kendra', 'kendra', 3794),
    new ServicePackage('mypy-boto3-cur', 'CostandUsageReportService', 3857),
    new ServicePackage('mypy-boto3-devicefarm', 'DeviceFarm', 4095),
    new ServicePackage('mypy-boto3-efs', 'EFS', 4041),
    new ServicePackage('mypy-boto3-mediastore', 'MediaStore', 3837),
    new ServicePackage('mypy-boto3-lookoutequipment', 'LookoutEquipment', 2523),
    new ServicePackage('mypy-boto3-groundstation', 'GroundStation', 3859),
    new ServicePackage('mypy-boto3-synthetics', 'Synthetics', 3572),
    new ServicePackage('mypy-boto3-servicecatalog', 'ServiceCatalog', 3940),
    new ServicePackage('mypy-boto3-budgets', 'Budgets', 3979),
    new ServicePackage('mypy-boto3-connectparticipant', 'ConnectParticipant', 3810),
    new ServicePackage('mypy-boto3-kinesisanalyticsv2', 'KinesisAnalyticsV2', 3884),
    new ServicePackage('mypy-boto3-ecs', 'ECS', 23013),
    new ServicePackage('mypy-boto3-globalaccelerator', 'GlobalAccelerator', 3883),
    new ServicePackage('mypy-boto3-firehose', 'Firehose', 8704),
    new ServicePackage('mypy-boto3-workdocs', 'WorkDocs', 3886),
    new ServicePackage('mypy-boto3-iot', 'IoT', 7292),
    new ServicePackage('mypy-boto3-neptune', 'Neptune', 3851),
    new ServicePackage('mypy-boto3-cloudfront', 'CloudFront', 7845),
    new ServicePackage('mypy-boto3-transfer', 'Transfer', 4715),
    new ServicePackage('mypy-boto3-codestar', 'CodeStar', 3939),
    new ServicePackage('mypy-boto3-snowball', 'Snowball', 4523),
    new ServicePackage('mypy-boto3-apprunner', 'AppRunner', 2426),
    new ServicePackage('mypy-boto3-alexaforbusiness', 'AlexaForBusiness', 3847),
    new ServicePackage('mypy-boto3-robomaker', 'RoboMaker', 3891),
    new ServicePackage('mypy-boto3-appflow', 'Appflow', 3342),
    new ServicePackage('mypy-boto3-ec2', 'EC2', 140139),
    new ServicePackage('mypy-boto3-cloudformation', 'CloudFormation', 80720),
    new ServicePackage('mypy-boto3-lakeformation', 'LakeFormation', 4028),
    new ServicePackage('mypy-boto3-wisdom', 'ConnectWisdomService', 1478),
    new ServicePackage('mypy-boto3-pricing', 'Pricing', 4709),
    new ServicePackage('mypy-boto3-braket', 'Braket', 3354),
    new ServicePackage('mypy-boto3-elasticbeanstalk', 'ElasticBeanstalk', 4169),
    new ServicePackage('mypy-boto3-iotwireless', 'IoTWireless', 3112),
    new ServicePackage('mypy-boto3-mediatailor', 'MediaTailor', 3902),
    new ServicePackage('mypy-boto3-appsync', 'AppSync', 3971),
    new ServicePackage('mypy-boto3-mq', 'MQ', 3911),
    new ServicePackage('mypy-boto3-ce', 'CostExplorer', 5272),
    new ServicePackage('mypy-boto3-wafv2', 'WAFV2', 4340),
    new ServicePackage('mypy-boto3-s3', 'S3', 869982),
    new ServicePackage('mypy-boto3-stepfunctions', 'SFN', 14092),
    new ServicePackage('mypy-boto3-datasync', 'DataSync', 4031),
    new ServicePackage('mypy-boto3-serverlessrepo', 'ServerlessApplicationRepository', 3881),
    new ServicePackage('mypy-boto3-elb', 'ElasticLoadBalancing', 4365),
    new ServicePackage('mypy-boto3-mgh', 'MigrationHub', 3853),
    new ServicePackage('mypy-boto3-athena', 'Athena', 13826),
    new ServicePackage('mypy-boto3-apigatewayv2', 'ApiGatewayV2', 4500),
    new ServicePackage('mypy-boto3-mwaa', 'MWAA', 3499),
    new ServicePackage('mypy-boto3-meteringmarketplace', 'MarketplaceMetering', 4606),
    new ServicePackage('mypy-boto3-sesv2', 'SESV2', 5366),
    new ServicePackage('mypy-boto3-appconfig', 'AppConfig', 3983),
    new ServicePackage('mypy-boto3-qldb', 'QLDB', 3881),
    new ServicePackage('mypy-boto3-glue', 'Glue', 31349),
    new ServicePackage('mypy-boto3-redshift', 'Redshift', 6308),
    new ServicePackage('mypy-boto3-clouddirectory', 'CloudDirectory', 3949),
    new ServicePackage('mypy-boto3-nimble', 'NimbleStudio', 2560),
    new ServicePackage('mypy-boto3-personalize', 'Personalize', 3888),
    new ServicePackage('mypy-boto3-sns', 'SNS', 28147),
    new ServicePackage('mypy-boto3-elastictranscoder', 'ElasticTranscoder', 4030),
    new ServicePackage('mypy-boto3-secretsmanager', 'SecretsManager', 80218),
    new ServicePackage('mypy-boto3-storagegateway', 'StorageGateway', 3930),
    new ServicePackage('mypy-boto3-glacier', 'Glacier', 3874),
    new ServicePackage('mypy-boto3-iotthingsgraph', 'IoTThingsGraph', 3850),
    new ServicePackage('mypy-boto3-workmail', 'WorkMail', 3873),
    new ServicePackage('mypy-boto3-ds', 'DirectoryService', 3872),
    new ServicePackage('mypy-boto3-xray', 'XRay', 4034),
    new ServicePackage('mypy-boto3-shield', 'Shield', 3953),
    new ServicePackage('mypy-boto3-organizations', 'Organizations', 4980),
    new ServicePackage('mypy-boto3-codedeploy', 'CodeDeploy', 7050),
    new ServicePackage('mypy-boto3-auditmanager', 'AuditManager', 3075),
    new ServicePackage('mypy-boto3-ecr', 'ECR', 17404),
    new ServicePackage('mypy-boto3-resiliencehub', 'ResilienceHub', 45),
    new ServicePackage('mypy-boto3-mediapackage', 'MediaPackage', 4239),
    new ServicePackage('mypy-boto3-location', 'LocationService', 3520),
    new ServicePackage('mypy-boto3-opsworkscm', 'OpsWorksCM', 3862),
    new ServicePackage('mypy-boto3-panorama', 'Panorama', 990),
    new ServicePackage('mypy-boto3-greengrass', 'Greengrass', 5212),
    new ServicePackage('mypy-boto3-backup', 'Backup', 3951),
    new ServicePackage('mypy-boto3-dataexchange', 'DataExchange', 3853),
    new ServicePackage('mypy-boto3-eks', 'EKS', 4926),
    new ServicePackage('mypy-boto3-macie', 'Macie', 3897),
    new ServicePackage('mypy-boto3-fms', 'FMS', 3871),
    new ServicePackage('mypy-boto3-rds', 'RDS', 80790),
    new ServicePackage('mypy-boto3-comprehend', 'Comprehend', 4512),
    new ServicePackage('mypy-boto3-appintegrations', 'AppIntegrationsService', 3109),
    new ServicePackage('mypy-boto3-support', 'Support', 3940),
    new ServicePackage('mypy-boto3-marketplacecommerceanalytics', 'MarketplaceCommerceAnalytics', 3833),
    new ServicePackage('mypy-boto3-iotevents', 'IoTEvents', 3882),
    new ServicePackage('mypy-boto3-logs', 'CloudWatchLogs', 11112),
    new ServicePackage('mypy-boto3-macie2', 'Macie2', 3509),
    new ServicePackage('mypy-boto3-acm', 'ACM', 10392),
    new ServicePackage('mypy-boto3-cloudhsmv2', 'CloudHSMV2', 3880),
    new ServicePackage('mypy-boto3-imagebuilder', 'imagebuilder', 3796),
    new ServicePackage('mypy-boto3-forecast', 'ForecastService', 3853),
    new ServicePackage('mypy-boto3-cloudhsm', 'CloudHSM', 3854),
    new ServicePackage('mypy-boto3-cloud9', 'Cloud9', 3890),
    new ServicePackage('mypy-boto3-batch', 'Batch', 43968),
    new ServicePackage('mypy-boto3-proton', 'Proton', 2375),
    new ServicePackage('mypy-boto3-wellarchitected', 'WellArchitected', 3060),
    new ServicePackage('mypy-boto3-savingsplans', 'SavingsPlans', 4177),
    new ServicePackage('mypy-boto3-inspector', 'Inspector', 4685),
    new ServicePackage('mypy-boto3-finspace', 'finspace', 2484),
    new ServicePackage('mypy-boto3-elasticache', 'ElastiCache', 6117),
    new ServicePackage('mypy-boto3-iotsitewise', 'IoTSiteWise', 3542),
    new ServicePackage('mypy-boto3-sdb', 'SimpleDB', 3915),
    new ServicePackage('mypy-boto3-amplify', 'Amplify', 4328),
    new ServicePackage('mypy-boto3-sagemaker-runtime', 'SageMakerRuntime', 4364),
    new ServicePackage('mypy-boto3-sagemaker-edge', 'SagemakerEdgeManager', 3074),
    new ServicePackage('mypy-boto3-migrationhub-config', 'MigrationHubConfig', 3822),
    new ServicePackage('mypy-boto3-sso-oidc', 'SSOOIDC', 4348),
    new ServicePackage('mypy-boto3-personalize-events', 'PersonalizeEvents', 3891),
    new ServicePackage('mypy-boto3-personalize-runtime', 'PersonalizeRuntime', 3857),
    new ServicePackage('mypy-boto3-finspace-data', 'FinSpaceData', 2486),
    new ServicePackage('mypy-boto3-qldb-session', 'QLDBSession', 3932),
    new ServicePackage('mypy-boto3-marketplace-entitlement', 'MarketplaceEntitlementService', 4257),
    new ServicePackage('mypy-boto3-elastic-inference', 'ElasticInference', 3796),
    new ServicePackage('mypy-boto3-iot-data', 'IoTDataPlane', 4982),
    new ServicePackage('mypy-boto3-timestream-query', 'TimestreamQuery', 3692),
    new ServicePackage('mypy-boto3-s3outposts', 'S3Outposts', 3213),
    new ServicePackage('mypy-boto3-mediastore-data', 'MediaStoreData', 3849),
    new ServicePackage('mypy-boto3-iot-jobs-data', 'IoTJobsDataPlane', 3821),
    new ServicePackage('mypy-boto3-chime-sdk-meetings', 'ChimeSDKMeetings', 260),
    new ServicePackage('mypy-boto3-route53-recovery-cluster', 'Route53RecoveryCluster', 2227),
    new ServicePackage('mypy-boto3-connect-contact-lens', 'ConnectContactLens', 3073),
    new ServicePackage('mypy-boto3-cognito-sync', 'CognitoSync', 3884),
    new ServicePackage('mypy-boto3-lex-runtime', 'LexRuntimeService', 3876),
    new ServicePackage('mypy-boto3-iotevents-data', 'IoTEventsData', 3900),
    new ServicePackage('mypy-boto3-codestar-connections', 'CodeStarconnections', 3778),
    new ServicePackage('mypy-boto3-ec2-instance-connect', 'EC2InstanceConnect', 4638),
    new ServicePackage('mypy-boto3-kinesis-video-signaling', 'KinesisVideoSignalingChannels', 3851),
    new ServicePackage('mypy-boto3-rds-data', 'RDSDataService', 4285),
    new ServicePackage('mypy-boto3-sms-voice', 'PinpointSMSVoice', 3920),
    new ServicePackage('mypy-boto3-application-insights', 'ApplicationInsights', 3952),
    new ServicePackage('mypy-boto3-kinesis-video-media', 'KinesisVideoMedia', 3839),
    new ServicePackage('mypy-boto3-marketplace-catalog', 'MarketplaceCatalog', 3818),
    new ServicePackage('mypy-boto3-sagemaker-featurestore-runtime', 'SageMakerFeatureStoreRuntime', 3166),
    new ServicePackage('mypy-boto3-timestream-write', 'TimestreamWrite', 4474),
    new ServicePackage('mypy-boto3-voice-id', 'VoiceID', 1515),
    new ServicePackage('mypy-boto3-pinpoint-sms-voice', 'PinpointSMSVoice', 3862),
    new ServicePackage('mypy-boto3-lexv2-runtime', 'LexRuntimeV2', 2908),
    new ServicePackage('mypy-boto3-service-quotas', 'ServiceQuotas', 4537),
    new ServicePackage('mypy-boto3-application-autoscaling', 'ApplicationAutoScaling', 6262),
    new ServicePackage('mypy-boto3-snow-device-management', 'SnowDeviceManagement', 2165),
    new ServicePackage('mypy-boto3-resource-groups', 'ResourceGroups', 3866),
    new ServicePackage('mypy-boto3-kinesis-video-archived-media', 'KinesisVideoArchivedMedia', 3862),
    new ServicePackage('mypy-boto3-sagemaker-a2i-runtime', 'AugmentedAIRuntime', 3878),
    new ServicePackage('mypy-boto3-emr-containers', 'EMRContainers', 3079),
    new ServicePackage('mypy-boto3-autoscaling-plans', 'AutoScalingPlans', 3881),
    new ServicePackage('mypy-boto3-codestar-notifications', 'CodeStarNotifications', 3931),
    new ServicePackage('mypy-boto3-servicecatalog-appregistry', 'AppRegistry', 3171),
    new ServicePackage('mypy-boto3-iot1click-projects', 'IoT1ClickProjects', 3944),
    new ServicePackage('mypy-boto3-mediapackage-vod', 'MediaPackageVod', 3840),
    new ServicePackage('mypy-boto3-cognito-identity', 'CognitoIdentity', 4226),
    new ServicePackage('mypy-boto3-ecr-public', 'ECRPublic', 3141),
    new ServicePackage('mypy-boto3-redshift-data', 'RedshiftDataAPIService', 3484),
    new ServicePackage('mypy-boto3-iot1click-devices', 'IoT1ClickDevicesService', 3865),
    new ServicePackage('mypy-boto3-ssm-contacts', 'SSMContacts', 2470),
    new ServicePackage('mypy-boto3-route53domains', 'Route53Domains', 4869),
    new ServicePackage('mypy-boto3-chime-sdk-identity', 'ChimeSDKIdentity', 2209),
    new ServicePackage('mypy-boto3-compute-optimizer', 'ComputeOptimizer', 4281),
    new ServicePackage('mypy-boto3-customer-profiles', 'CustomerProfiles', 3093),
    new ServicePackage('mypy-boto3-codeguru-reviewer', 'CodeGuruReviewer', 3899),
    new ServicePackage('mypy-boto3-acm-pca', 'ACMPCA', 3907),
    new ServicePackage('mypy-boto3-route53-recovery-control-config', 'Route53RecoveryControlConfig', 2232),
    new ServicePackage('mypy-boto3-devops-guru', 'DevOpsGuru', 3093),
    new ServicePackage('mypy-boto3-route53-recovery-readiness', 'Route53RecoveryReadiness', 2238),
    new ServicePackage('mypy-boto3-sso-admin', 'SSOAdmin', 3316),
    new ServicePackage('mypy-boto3-network-firewall', 'NetworkFirewall', 3176),
    new ServicePackage('mypy-boto3-pinpoint-email', 'PinpointEmail', 3854),
    new ServicePackage('mypy-boto3-chime-sdk-messaging', 'ChimeSDKMessaging', 2213),
    new ServicePackage('mypy-boto3-ssm-incidents', 'SSMIncidents', 2465),
    new ServicePackage('mypy-boto3-s3control', 'S3Control', 5488),
    new ServicePackage('mypy-boto3-license-manager', 'LicenseManager', 3840),
    new ServicePackage('mypy-boto3-lex-models', 'LexModelBuildingService', 3915),
    new ServicePackage('mypy-boto3-waf-regional', 'WAFRegional', 4125),
    new ServicePackage('mypy-boto3-lexv2-models', 'LexModelsV2', 2897),
    new ServicePackage('mypy-boto3-route53resolver', 'Route53Resolver', 3884),
    new ServicePackage('mypy-boto3-cognito-idp', 'CognitoIdentityProvider', 17644),
];
